
CREATE TABLE Material
(
	RowIdObject INT NOT NULL PRIMARY KEY,
	Creator	VARCHAR(200),
	CreateDate DATETIME2,
	UpdatedBy VARCHAR(200),
	LastUpdateDate DATETIME2,
	ConsolidationInd FLOAT NOT NULL,
	DeletedInd FLOAT,
	DeletedBy VARCHAR(200),
	DeletedDate	DATETIME2,
	LastRowidSystem	VARCHAR(56) NOT NULL,
	DirtyInd FLOAT,
	InteractionId FLOAT,
	HubStateInd	FLOAT NOT NULL,
	CmDirtyInd FLOAT,
	SapMaterialId BIGINT,
	SapMaterialTypeCd VARCHAR(16),
	SapMaterialGroupCd VARCHAR(36),
	SapBaseUnitOfMsrCd VARCHAR(12),
	PartDs VARCHAR(160),
	SapMaterialStatusCd	VARCHAR(8),
	SapMatItemCatgGroupCd VARCHAR(16),
	SapOrderUnitOfMsureCd VARCHAR(12),
	SapMatGroupPackagingCd VARCHAR(16),
	ManufactFamilyPartNo VARCHAR(192),
	ItarFl VARCHAR(4),
	SupplierLastTimeBuyDt DATE,
	SupplierLastTimeShipDt DATE,
	SupplierLastTimeRetDt DATE,
	SapMatIndstrySectorCd VARCHAR(4),
	AvnetLegacyPartId VARCHAR(160),
	MaterialStatusDt DATE,
	ManufacturerPartNo VARCHAR(160),
	GrossWeightQt DECIMAL(13,3),
	NetWeightQt	DECIMAL(13,3),
	SapWtUnitOfMeasureCd VARCHAR(12),
	VolumeQt DECIMAL(13,3),
	SapVolUnitOfMeasureCd VARCHAR(12),
	SizeDimensionsDs VARCHAR(128),
	SapPurchasingValueCd VARCHAR(16),
	DimensionLengthQt DECIMAL(13,3),
	DimensionWidthQt DECIMAL(13,3),
	DimensionHeightQt DECIMAL(13,3),
	SapDimUnitOfMeasureCd VARCHAR(12),
	TradeComplianceNoteTx VARCHAR(800),
	ExportControlClassNo VARCHAR(60),
	SapScheduleBCd VARCHAR(60),
	CcatsEncryptionRegNo VARCHAR(28),
	SapRohsCd VARCHAR(4),
	SapGreenCd VARCHAR(4),
	SapWstsCd VARCHAR(12),
	MilitarySpecPartNo VARCHAR(120),
	CustomReelableFl VARCHAR(4),
	SapLeadFreeCd VARCHAR(4),
	SapEcomStockStrategyCd VARCHAR(4),
	FccFl VARCHAR(4),
	SapTlaTypeCd VARCHAR(20),
	WarrantyDurationMonthQt	FLOAT,
	AvnetValueAddNo VARCHAR(120),
	DemoPartValueAm	DECIMAL(10,2),
	FactoryStockAvailQt	DECIMAL(13,3),
	MdmUsmlCd VARCHAR(44),
	MdmWebCd VARCHAR(4),
	SoleSourceFl VARCHAR(4),
	TransactablePartFl VARCHAR(4),
	MdmUnspscCd VARCHAR(48),
	FdaFl VARCHAR(4),
	SignedLicAgrmntReqFl VARCHAR(4),
	InspectionTx VARCHAR(120),
	SapJitCd VARCHAR(4),
	MdmSmxqDeviationCd VARCHAR(4),
	ValueAddedFl VARCHAR(4),
	MdmActionCd	VARCHAR(20),
	MaterialDs VARCHAR(800),
	MdmManufacturerPartyId VARCHAR(56),
	ProgrammableFl VARCHAR(4),
	ReplacementPartNo VARCHAR(176),
	SapExternalMatlGroup VARCHAR(72),
	SapSerialNoLevelCd VARCHAR(4),
	SapTransGroupCd VARCHAR(16),
	EconomicProductionQt FLOAT,
	SapStorageConditionCd VARCHAR(8),
	MaterialProdHierarchyId	INT,
	SendToSapFl VARCHAR(4),
	SentToSapDate DATE,
	SapProductHierarchyCd VARCHAR(72),
	RenewableFl	VARCHAR(4),
	MaterialSuppressSyndFl VARCHAR(4),
	ResyndFl VARCHAR(4),
	TaskRequesterEmail VARCHAR(1020),
	InventoryMessageTx VARCHAR(800),
	ProcurementStrategy VARCHAR(12),
	PackageQty BIGINT,
	SqlStartTime datetime2 GENERATED ALWAYS AS ROW START NOT NULL,
    SqlEndTime datetime2 GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME (SqlStartTime, SqlEndTime),
	CONSTRAINT FKMatMatProdHier FOREIGN KEY(MaterialProdHierarchyId)
	REFERENCES [dbo].[MaterialProdHier] (RowIdObject)
)
WITH
	(
		SYSTEM_VERSIONING = ON (HISTORY_TABLE= dbo.MaterialHistory)
	)
;