Select 
Max(Mth00TagMth) As Mth00Tag,
Max(Mth01TagMth) As Mth01Tag, 
Max(Mth02TagMth) As Mth02Tag, 
Max(Mth03TagMth) As Mth03Tag, 
Max(Mth04TagMth) As Mth04Tag, 
Max(Mth05TagMth) As Mth05Tag, 
Max(Mth06TagMth) As Mth06Tag, 
Max(Mth07TagMth) As Mth07Tag, 
Max(Mth08TagMth) As Mth08Tag, 
Max(Mth09TagMth) As Mth09Tag, 
Max(Mth10TagMth) As Mth10Tag, 
Max(Mth11TagMth) As Mth11Tag, 
Max(Mth12TagMth) As Mth12Tag, 
Max(Mth13TagMth) As Mth13Tag
From (Select distinct 
Case When RDA.FyMthNbr+0=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth00TagMth,
Case When RDA.FyMthNbr+1=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth01TagMth,
Case When RDA.FyMthNbr+2=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth02TagMth,
Case When RDA.FyMthNbr+3=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth03TagMth,
Case When RDA.FyMthNbr+4=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth04TagMth,
Case When RDA.FyMthNbr+5=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth05TagMth,
Case When RDA.FyMthNbr+6=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth06TagMth,
Case When RDA.FyMthNbr+7=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth07TagMth,
Case When RDA.FyMthNbr+8=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth08TagMth,
Case When RDA.FyMthNbr+9=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth09TagMth,
Case When RDA.FyMthNbr+10=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth10TagMth,
Case When RDA.FyMthNbr+11=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth11TagMth,
Case When RDA.FyMthNbr+12=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth12TagMth,
Case When RDA.FyMthNbr+13=RDAT.FyMthNbr Then RDA.FyTagMth Else Null End As Mth13TagMth From CentralDbs.dbo.RefDateAvnet as RDA cross join CentralDbs.dbo.RefDateAvnet as RDAT where Cast(RDA.DateDt as Date) >= Cast(Getdate()-400 as date) and Cast(RDA.DateDt as Date) <= Cast(Getdate() as date)  and Cast(RDAT.DateDt as date) = Cast(GetDate() as date)) as iq1