


INSERT INTO bi.dbo.sobackloghistory 
(VersionDt,
LogDt,
LogTime,
SalesDocNbr,
SalesDocItemNbr,
SoSchedLine,
PlantId,
MaterialNbr,
MfgPartNbr,
FyMthNbr,
OutsideSalesRep,
InsideSalesRep,
SoldToPartyId,
SoldToParty,
SalesDocItCreateDt,
CustomerPoNbr,
CustomerPartNbr,
MaterialTxt,
Grp,
Pbg,
Cc,
Mfg,
PrcStgy,
Tech,
BillingBlock,
PricingBlock,
ShipAndDebitBlock,
CreditBlock,
DlvryBlock,
ProgrammingBlock,
CustReqDockDt,
LastConfPromDt,
DlvryDt,
OrginPromDt,
AtpDt,
OrderQty,
RemainingQty,
UnitPrice,
ExtResale,
TtlOrderValue,
MrpCntrl,
Abc,
StockProfile,
OrderReason,
BufferType,
PlantSpecificMatl,
SalesDocType,
ResaleSource,
PurGrp,
BlockedOrders,
SalesOrg,
SalesOffice,
SalesGrp,
MatBaseUnit,
CondType,
OverallDlvryStatus,
ExtCost,
MatGpPercent,
DlvryStatus
,SqlStartTime
,SqlEndTime)

SELECT 
version_dt,
CAST([log_dt] AS DATETIME2) as log_dt,
CAST([log_time] AS TIME) as log_time,
Try_cast([sales_doc_nbr] as bigint) as sales_doc_nbr,
Try_cast([sales_doc_item_nbr] as int) as sales_doc_item_nbr,
Try_cast([sched_line] as int) as sched_line,
Try_cast([plant_id] AS int) as plant_id,
Try_Cast([material_nbr] as bigint) as material_nbr,
mfg_part_nbr,
Try_cast([fy_mth_nbr] as int) as fy_mth_nbr,
outside_sales_rep,
inside_sales_rep,
Try_cast([sold_to_party_id] as int) as sold_to_part_id,
sold_to_party,
Try_cast([sales_doc_it_create_dt] as datetime2) as sales_doc_it_create_dt,
customer_po_nbr,
customer_part_nbr,
material_txt,
grp,
pbg,
CC,
mfg,
prc_stgy,
tech,
billing_block,
pricing_block,
ship_and_debit_block,
credit_block,
dlvry_block,
programming_block,
try_cast([cust_req_dock_dt] as datetime2) as [cust_req_dock_dt],
try_cast([last_conf_prom_dt] as datetime2) as [last_conf_prom_dt],
try_cast([dlvry_dt] as datetime2) as [dlvry_dt],
try_cast([orgin_prom_dt] as datetime2) as [orgin_prom_dt],
try_cast([ATP_dt] as datetime2) as [ATP_dt],
try_cast([order_qty] as bigint) as [order_qty],
try_cast([remaining_qty] as bigint) as [remaining_qty],
try_cast([unit_price] as money) as [unit_price],
try_cast([ext_resale] as money) as [ext_resale], 
try_cast([ttl_order_value] as money) as [ttl_order_value],
mrp_cntrl,
abc,
stock_profile,
order_reason,
buffer_type,
plant_specific_matl,
sales_doc_type,
resale_source,
pur_grp,
try_cast([blocked_orders] as bigint) as [blocked_orders],
sales_org,
try_cast([sales_office] as int) as [sales_office],
try_cast([sales_grp] as int) as [sales_grp],
mat_base_unit,
cond_type,
overall_dlvry_status,
try_cast([ext_cost] as money) as [ext_cost],
try_cast([mat_gp%] as int) as [mat_gp%],
dlvry_status,
CAST([log_dt] AS DATETIME2),
CAST([log_dt] AS DATETIME2)
FROM NonHaImportTesting.dbo.sales_order_backlog_history
GO 
