USE Interfaces
GO

/****** Object:  Table [dbo].[LinQtc305QuoteLine]    Script Date: 11/2/2017 2:45:02 PM ******/
ALTER TABLE [dbo].[LinQtc305QuoteLine] SET ( SYSTEM_VERSIONING = OFF  )
GO

/****** Object:  Table [dbo].[LinQtc305QuoteLine]    Script Date: 11/2/2017 2:45:02 PM ******/
DROP TABLE [dbo].[LinQtc305QuoteLine]
GO

/****** Object:  Table [dbo].[LinQtc305QuoteLineHistory]    Script Date: 11/2/2017 2:45:02 PM ******/
DROP TABLE [dbo].[LinQtc305QuoteLineHistory]
GO

/****** Object:  Table [dbo].[LinQtc305QuoteLineHistory]    Script Date: 11/2/2017 2:45:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LinQtc305QuoteLineHistory](
	[QuoteId] [int] NOT NULL,
	[QuoteLineNbr] [int] NOT NULL,
	[AdditionalChargeAmt1] [decimal](15, 5) NULL,
	[AdditionalChargeAmt2] [decimal](15, 5) NULL,
	[AdditionalCostAmt1] [decimal](15, 5) NULL,
	[AdditionalCostAmt1UoFlag] [varchar](1) NULL,
	[AdditionalCostAmt2] [decimal](15, 5) NULL,
	[AdditionalCostAmt2UoFlag] [varchar](1) NULL,
	[AdditionalUnitChargeAmt] [decimal](15, 5) NULL,
	[AdditionalUnitChargeAmtUoFlag] [varchar](1) NULL,
	[AdditionalUnitCostAmt] [decimal](15, 5) NULL,
	[AdditionalUnitCostAmtUoFlag] [varchar](1) NULL,
	[AuthAdditionalInfoNeededFlag] [varchar](1) NULL,
	[AuthAssignedToUserId] [varchar](30) NULL,
	[AuthAssignmentDt] [datetime2](7) NULL,
	[AuthBomDiscountCostPct] [decimal](15, 5) NULL,
	[AuthFollowUpDt] [datetime2](7) NULL,
	[AuthNoBidFlag] [varchar](1) NULL,
	[AuthNoBidSetByUserId] [varchar](30) NULL,
	[AuthNoBidSetDt] [datetime2](7) NULL,
	[AuthProductCompletedByUserId] [varchar](30) NULL,
	[AuthProductCompletedDt] [datetime2](7) NULL,
	[AuthProductFlag] [varchar](1) NULL,
	[AuthSubmittedToSupplierFlag] [varchar](1) NULL,
	[AuthSupplierQuoteId] [varchar](30) NULL,
	[AwardRequoteId] [int] NULL,
	[CustomerLineNbr] [varchar](10) NULL,
	[CustomerPartNbr] [varchar](50) NULL,
	[CustomerRequireOnDockDt] [date] NULL,
	[CustomerRequireOnDockDtUoFlag] [varchar](1) NULL,
	[CustomerReference1Tx] [varchar](30) NULL,
	[CustomerReference2Tx] [varchar](30) NULL,
	[CustomerSoftwareLicenseId] [int] NULL,
	[CustomerSpecificationDs] [varchar](30) NULL,
	[DisplayLineNbr] [varchar](30) NULL,
	[DrawingRefNbr] [varchar](30) NULL,
	[EcommerceQuoteLineNbr] [int] NULL,
	[EndCustomerUoFlag] [varchar](1) NULL,
	[EnterpriseConfigCompleteFlag] [varchar](1) NULL,
	[EnterpriseConfigFlag] [varchar](1) NULL,
	[ExtendedResaleAmt] [decimal](15, 5) NULL,
	[FieldSalesRepId] [varchar](30) NULL,
	[FirstArticleSerialNbr] [varchar](30) NULL,
	[FirstArticleSerialNbrFlag] [varchar](1) NULL,
	[InsideSalesRepUserId] [varchar](30) NULL,
	[LostSaleReasonCd] [varchar](3) NULL,
	[MdmCustomerMaterialId] [varchar](15) NULL,
	[MdmEndCustomerPartyId] [varchar](15) NULL,
	[MdmEndUserCustomerPartyId] [varchar](15) NULL,
	[MdmMaterialId] [varchar](15) NULL,
	[MdmShipToCustomerPartyId] [varchar](15) NULL,
	[MdmSoldToCustomerPartyId] [varchar](15) NULL,
	[NoBidReason] [int] NULL,
	[OriginalRequestedMfrName] [varchar](50) NULL,
	[OriginalRequestedPartNbr] [varchar](50) NULL,
	[PartMatchMethodCd] [varchar](3) NOT NULL,
	[PaCostAdderPct] [int] NULL,
	[PaCurrentAvailableInventoryQty] [bigint] NULL,
	[PreviousQuoteLineStatusCd] [varchar](3) NULL,
	[ProjectBoardName] [varchar](50) NULL,
	[QuoteLineCreateDt] [date] NOT NULL,
	[QuoteLineCreateUserId] [varchar](30) NOT NULL,
	[QuoteLineStatusCd] [varchar](3) NOT NULL,
	[ReadyForDeliveryFlag] [varchar](1) NULL,
	[RequestedMfrName] [varchar](50) NULL,
	[RequestedPartNbr] [varchar](50) NULL,
	[RequestedPartDs] [varchar](max) NULL,
	[SalesDueDt] [datetime2](7) NULL,
	[SapCommodityCd] [varchar](3) NULL,
	[SapSalesOfficeCd] [varchar](4) NULL,
	[SapSalesOrderNbr] [varchar](15) NULL,
	[SapSalesOrderCd] [varchar](4) NULL,
	[SapSpecialHandlingCd] [varchar](5) NULL,
	[ShipWithQuoteLineNbr] [int] NULL,
	[SilverCreekMfrName] [varchar](50) NULL,
	[SilverCreekPartNbr] [varchar](50) NULL,
	[SpecialHandlingCdUoFlag] [varchar](1) NULL,
	[SubdivideRequestColChangeTx] [varchar](max) NULL,
	[ValueAddServiceCd] [varchar](3) NULL,
	[ValueAddServiceUoFlag] [varchar](1) NULL,
	[ApplCreateDt] [datetime2](7) NOT NULL,
	[ApplUpdateDt] [datetime2](7) NOT NULL,
	[ApplActiveFromDt] [datetime2](7) NOT NULL,
	[ApplActiveThruDt] [datetime2](7) NOT NULL,
	[SapMaterialTypeCd] [varchar](4) NULL,
	[SapShipToCustomerAcctGrpCd] [varchar](4) NULL,
	[SapSoldToCustomerAcctGrpCd] [varchar](4) NULL,
	[SapTlaTypeCd] [varchar](5) NULL,
	[MdmPayerCustomerPartyId] [varchar](15) NULL,
	[ProductSpecialistAssignFlag] [varchar](1) NULL,
	[SapPriceBlockCd] [varchar](2) NULL,
	[OriginalRequestTlaNbr] [varchar](50) NULL,
	[RequestTlaNbr] [varchar](50) NULL,
	[SapAdditionalChargeReasonCd1] [varchar](3) NULL,
	[SapAdditionalChargeReasonCd2] [varchar](3) NULL,
	[SapAdditionalUnitCostReason2Cd] [varchar](3) NULL,
	[SapSupplierVendorCd] [varchar](3) NULL,
	[SapMfrVendorId] [varchar](15) NULL,
	[RequestSapSupplierVendorCd] [varchar](3) NULL,
	[OriginalRequestSapSupplierVendorCd] [varchar](3) NULL,
	[SapMaterialItemCategoryGrpCd] [varchar](4) NULL,
	[ParentQuoteLineNbr] [int] NULL,
	[MultipleSupplierSourceFlag] [varchar](1) NULL,
	[SapMarkingInstructionCd] [varchar](1) NULL,
	[BomCompPriorityNbr] [int] NULL,
	[SapMaterialStatusCd] [varchar](2) NULL,
	[CossSellTlaFlag] [varchar](1) NULL,
	[RegistrationMatchMethodCd] [varchar](3) NULL,
	[ConfigLineNo] [varchar](15) NULL,
	[FinishedTlaFl] [char](1) NULL,
	[FormattedDisplayLineNo] [varchar](30) NULL,
	[NonCancelNonReturnFl] [char](1) NULL,
	[PaLastRefreshDt] [datetime2](7) NULL,
	[LastRefreshedByUserId] [varchar](max) NULL,
	[BiProductSpecialistAssgnFl] [char](1) NULL,
	[NascarExportDt] [datetime2](7) NULL,
	[NascarFailedResponseQt] [int] NULL,
	[NascarImportErrorCd] [varchar](1024) NULL,
	[NascarProdSubmitQt] [int] NULL,
	[NascarProgressAuthTypeCd] [varchar](2) NULL,
	[NascarSentFl] [varchar](2) NULL,
	[SqlStartTime] [datetime2](7) NOT NULL,
	[SqlEndTime] [datetime2](7) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

/****** Object:  Table [dbo].[LinQtc305QuoteLine]    Script Date: 11/2/2017 2:45:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LinQtc305QuoteLine](
	[QuoteId] [int] NOT NULL,
	[QuoteLineNbr] [int] NOT NULL,
	[AdditionalChargeAmt1] [decimal](15, 5) NULL,
	[AdditionalChargeAmt2] [decimal](15, 5) NULL,
	[AdditionalCostAmt1] [decimal](15, 5) NULL,
	[AdditionalCostAmt1UoFlag] [varchar](1) NULL,
	[AdditionalCostAmt2] [decimal](15, 5) NULL,
	[AdditionalCostAmt2UoFlag] [varchar](1) NULL,
	[AdditionalUnitChargeAmt] [decimal](15, 5) NULL,
	[AdditionalUnitChargeAmtUoFlag] [varchar](1) NULL,
	[AdditionalUnitCostAmt] [decimal](15, 5) NULL,
	[AdditionalUnitCostAmtUoFlag] [varchar](1) NULL,
	[AuthAdditionalInfoNeededFlag] [varchar](1) NULL,
	[AuthAssignedToUserId] [varchar](30) NULL,
	[AuthAssignmentDt] [datetime2](7) NULL,
	[AuthBomDiscountCostPct] [decimal](15, 5) NULL,
	[AuthFollowUpDt] [datetime2](7) NULL,
	[AuthNoBidFlag] [varchar](1) NULL,
	[AuthNoBidSetByUserId] [varchar](30) NULL,
	[AuthNoBidSetDt] [datetime2](7) NULL,
	[AuthProductCompletedByUserId] [varchar](30) NULL,
	[AuthProductCompletedDt] [datetime2](7) NULL,
	[AuthProductFlag] [varchar](1) NULL,
	[AuthSubmittedToSupplierFlag] [varchar](1) NULL,
	[AuthSupplierQuoteId] [varchar](30) NULL,
	[AwardRequoteId] [int] NULL,
	[CustomerLineNbr] [varchar](10) NULL,
	[CustomerPartNbr] [varchar](50) NULL,
	[CustomerRequireOnDockDt] [date] NULL,
	[CustomerRequireOnDockDtUoFlag] [varchar](1) NULL,
	[CustomerReference1Tx] [varchar](30) NULL,
	[CustomerReference2Tx] [varchar](30) NULL,
	[CustomerSoftwareLicenseId] [int] NULL,
	[CustomerSpecificationDs] [varchar](30) NULL,
	[DisplayLineNbr] [varchar](30) NULL,
	[DrawingRefNbr] [varchar](30) NULL,
	[EcommerceQuoteLineNbr] [int] NULL,
	[EndCustomerUoFlag] [varchar](1) NULL,
	[EnterpriseConfigCompleteFlag] [varchar](1) NULL,
	[EnterpriseConfigFlag] [varchar](1) NULL,
	[ExtendedResaleAmt] [decimal](15, 5) NULL,
	[FieldSalesRepId] [varchar](30) NULL,
	[FirstArticleSerialNbr] [varchar](30) NULL,
	[FirstArticleSerialNbrFlag] [varchar](1) NULL,
	[InsideSalesRepUserId] [varchar](30) NULL,
	[LostSaleReasonCd] [varchar](3) NULL,
	[MdmCustomerMaterialId] [varchar](15) NULL,
	[MdmEndCustomerPartyId] [varchar](15) NULL,
	[MdmEndUserCustomerPartyId] [varchar](15) NULL,
	[MdmMaterialId] [varchar](15) NULL,
	[MdmShipToCustomerPartyId] [varchar](15) NULL,
	[MdmSoldToCustomerPartyId] [varchar](15) NULL,
	[NoBidReason] [int] NULL,
	[OriginalRequestedMfrName] [varchar](50) NULL,
	[OriginalRequestedPartNbr] [varchar](50) NULL,
	[PartMatchMethodCd] [varchar](3) NOT NULL,
	[PaCostAdderPct] [int] NULL,
	[PaCurrentAvailableInventoryQty] [bigint] NULL,
	[PreviousQuoteLineStatusCd] [varchar](3) NULL,
	[ProjectBoardName] [varchar](50) NULL,
	[QuoteLineCreateDt] [date] NOT NULL,
	[QuoteLineCreateUserId] [varchar](30) NOT NULL,
	[QuoteLineStatusCd] [varchar](3) NOT NULL,
	[ReadyForDeliveryFlag] [varchar](1) NULL,
	[RequestedMfrName] [varchar](50) NULL,
	[RequestedPartNbr] [varchar](50) NULL,
	[RequestedPartDs] [varchar](max) NULL,
	[SalesDueDt] [datetime2](7) NULL,
	[SapCommodityCd] [varchar](3) NULL,
	[SapSalesOfficeCd] [varchar](4) NULL,
	[SapSalesOrderNbr] [varchar](15) NULL,
	[SapSalesOrderCd] [varchar](4) NULL,
	[SapSpecialHandlingCd] [varchar](5) NULL,
	[ShipWithQuoteLineNbr] [int] NULL,
	[SilverCreekMfrName] [varchar](50) NULL,
	[SilverCreekPartNbr] [varchar](50) NULL,
	[SpecialHandlingCdUoFlag] [varchar](1) NULL,
	[SubdivideRequestColChangeTx] [varchar](max) NULL,
	[ValueAddServiceCd] [varchar](3) NULL,
	[ValueAddServiceUoFlag] [varchar](1) NULL,
	[ApplCreateDt] [datetime2](7) NOT NULL,
	[ApplUpdateDt] [datetime2](7) NOT NULL,
	[ApplActiveFromDt] [datetime2](7) NOT NULL,
	[ApplActiveThruDt] [datetime2](7) NOT NULL,
	[SapMaterialTypeCd] [varchar](4) NULL,
	[SapShipToCustomerAcctGrpCd] [varchar](4) NULL,
	[SapSoldToCustomerAcctGrpCd] [varchar](4) NULL,
	[SapTlaTypeCd] [varchar](5) NULL,
	[MdmPayerCustomerPartyId] [varchar](15) NULL,
	[ProductSpecialistAssignFlag] [varchar](1) NULL,
	[SapPriceBlockCd] [varchar](2) NULL,
	[OriginalRequestTlaNbr] [varchar](50) NULL,
	[RequestTlaNbr] [varchar](50) NULL,
	[SapAdditionalChargeReasonCd1] [varchar](3) NULL,
	[SapAdditionalChargeReasonCd2] [varchar](3) NULL,
	[SapAdditionalUnitCostReason2Cd] [varchar](3) NULL,
	[SapSupplierVendorCd] [varchar](3) NULL,
	[SapMfrVendorId] [varchar](15) NULL,
	[RequestSapSupplierVendorCd] [varchar](3) NULL,
	[OriginalRequestSapSupplierVendorCd] [varchar](3) NULL,
	[SapMaterialItemCategoryGrpCd] [varchar](4) NULL,
	[ParentQuoteLineNbr] [int] NULL,
	[MultipleSupplierSourceFlag] [varchar](1) NULL,
	[SapMarkingInstructionCd] [varchar](1) NULL,
	[BomCompPriorityNbr] [int] NULL,
	[SapMaterialStatusCd] [varchar](2) NULL,
	[CossSellTlaFlag] [varchar](1) NULL,
	[RegistrationMatchMethodCd] [varchar](3) NULL,
	[ConfigLineNo] [varchar](15) NULL,
	[FinishedTlaFl] [char](1) NULL,
	[FormattedDisplayLineNo] [varchar](30) NULL,
	[NonCancelNonReturnFl] [char](1) NULL,
	[PaLastRefreshDt] [datetime2](7) NULL,
	[LastRefreshedByUserId] [varchar](max) NULL,
	[BiProductSpecialistAssgnFl] [char](1) NULL,
	[NascarExportDt] [datetime2](7) NULL,
	[NascarFailedResponseQt] [int] NULL,
	[NascarImportErrorCd] [varchar](1024) NULL,
	[NascarProdSubmitQt] [int] NULL,
	[NascarProgressAuthTypeCd] [varchar](2) NULL,
	[NascarSentFl] [varchar](2) NULL,
	[SqlStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SqlEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PkLinQtc305QuoteLine] PRIMARY KEY CLUSTERED 
(
	[QuoteId] ASC,
	[QuoteLineNbr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SqlStartTime], [SqlEndTime])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [dbo].[LinQtc305QuoteLineHistory] )
)

GO


