
MERGE Sap.dbo.Ekko AS TargetTbl
USING NonHaImportTesting.dbo.ImportEkko AS SourceTbl
ON (TargetTbl.PoNbr=SourceTbl.[Column 1])
WHEN MATCHED AND SourceTbl.[Column 0] Is Not Null and SourceTbl.[Column 0] <> ' '
	AND TargetTbl.[ChangedDt]<>Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 8],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 8],5,0,'/'),8,0,'/') End
THEN
	UPDATE SET
		TargetTbl.[Client]=SourceTbl.[Column 0]
		,TargetTbl.[PoNbr]=SourceTbl.[Column 1]
		,TargetTbl.[CoCd]=SourceTbl.[Column 2]
		,TargetTbl.[PoCat]=SourceTbl.[Column 3]
		,TargetTbl.[PurReqDocType]=SourceTbl.[Column 4]
		,TargetTbl.[ControlId]=SourceTbl.[Column 5]
		,TargetTbl.[PurOrgData]=SourceTbl.[Column 6]
		,TargetTbl.[Status]=SourceTbl.[Column 7]
		,TargetTbl.[ChangedDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 8],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 8],5,0,'/'),8,0,'/') End
		,TargetTbl.[CreatedBy]=SourceTbl.[Column 9]
		,TargetTbl.[ItmNbrInterval]=SourceTbl.[Column 10]
		,TargetTbl.[LastItmNbr]=SourceTbl.[Column 11]
		,TargetTbl.[VenAccNbr]=CASE WHEN TRY_CAST(SourceTbl.[Column 12] AS BIGINT) IS NULL AND LEN(SourceTbl.[Column 12])=5 THEN RIGHT(SourceTbl.[Column 12],4) WHEN TRY_CAST(SourceTbl.[Column 12] AS BIGINT) IS NOT NULL AND LEN(SourceTbl.[Column 12])>3 THEN CAST(SourceTbl.[Column 12] AS BIGINT) END
		,TargetTbl.[Language]=SourceTbl.[Column 13]
		,TargetTbl.[PaytTerms]=SourceTbl.[Column 14]
		,TargetTbl.[DiscDays1]=Replace(SourceTbl.[Column 15],'.','')
		,TargetTbl.[DiscDays2]=Replace(SourceTbl.[Column 16],'.','')
		,TargetTbl.[DiscDays3]=Replace(SourceTbl.[Column 17],'.','')
		,TargetTbl.[DiscPct1]=SourceTbl.[Column 18]
		,TargetTbl.[DiscPct2]=SourceTbl.[Column 19]
		,TargetTbl.[PurchOrg]=SourceTbl.[Column 20]
		,TargetTbl.[PurGrp]=SourceTbl.[Column 21]
		,TargetTbl.[OrderCurr]=SourceTbl.[Column 22]
		,TargetTbl.[ExchangeRate]=SourceTbl.[Column 23]
		,TargetTbl.[ExchRateFixed]=SourceTbl.[Column 24]
		,TargetTbl.[PoDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 25],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 25],5,0,'/'),8,0,'/') End
		,TargetTbl.[ValidStartDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 26],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 26],5,0,'/'),8,0,'/') End
		,TargetTbl.[ValidEndDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 27],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 27],5,0,'/'),8,0,'/') End
		,TargetTbl.[AppClosingDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 28],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 28],5,0,'/'),8,0,'/') End
		,TargetTbl.[BidSubmissionDeadline]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 29],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 29],5,0,'/'),8,0,'/') End
		,TargetTbl.[BIdPeriodQuote]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 30],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 30],5,0,'/'),8,0,'/') End
		,TargetTbl.[WarrantyStartDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 31],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 31],5,0,'/'),8,0,'/') End
		,TargetTbl.[BidInvitationNbr]=Case When SourceTbl.[Column 32] = ' ' Then Null Else SourceTbl.[Column 32] End
		,TargetTbl.[QuoteNbr]=SourceTbl.[Column 33]
		,TargetTbl.[QuoteSubmissionDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 34],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 34],5,0,'/'),8,0,'/') End
		,TargetTbl.[YourRef]=SourceTbl.[Column 35]
		,TargetTbl.[SalesPersonResp]=SourceTbl.[Column 36]
		,TargetTbl.[VenTeleNbr]=SourceTbl.[Column 37]
		,TargetTbl.[SuppVendor]=SourceTbl.[Column 38]
		,TargetTbl.[SoldToPartyId]=Case When SourceTbl.[Column 39] = ' ' Then Null Else SourceTbl.[Column 39] End
		,TargetTbl.[Agreement]=SourceTbl.[Column 40]
		,TargetTbl.[RejectionReason]=SourceTbl.[Column 41]
		,TargetTbl.[CompleteDlvry]=SourceTbl.[Column 42]
		,TargetTbl.[GrMessage]=SourceTbl.[Column 43]
		,TargetTbl.[SupplyingPlant]=CASE WHEN ISNUMERIC(SourceTbl.[Column 44]) IS NULL THEN NULL ELSE SourceTbl.[Column 44] END
		,TargetTbl.[ReceivedVendor]=SourceTbl.[Column 45]
		,TargetTbl.[Incoterms1]=SourceTbl.[Column 46]
		,TargetTbl.[Incoterms2]=SourceTbl.[Column 47]
		,TargetTbl.[TargetVal]=SourceTbl.[Column 48]
		,TargetTbl.[CollectiveNbr]=Case When SourceTbl.[Column 49] = ' ' Then Null Else SourceTbl.[Column 49] End
		,TargetTbl.[DocCondNbr]=Case When SourceTbl.[Column 50] = ' ' Then Null Else SourceTbl.[Column 50] End
		,TargetTbl.[CostingSheet]=SourceTbl.[Column 51]
		,TargetTbl.[UpdateGrp]=SourceTbl.[Column 52]
		,TargetTbl.[InvoicingParty]=SourceTbl.[Column 53]
		,TargetTbl.[ForeignTradeDataNbr]=Case When SourceTbl.[Column 54] = ' ' Then Null Else SourceTbl.[Column 54] End
		,TargetTbl.[OurReference]=SourceTbl.[Column 55]
		,TargetTbl.[LogicalSys]=SourceTbl.[Column 56]
		,TargetTbl.[SubItmNbr]=SourceTbl.[Column 57]
		,TargetTbl.[DocTimeDepCond]=SourceTbl.[Column 58]
		,TargetTbl.[RelGrp]=SourceTbl.[Column 59]
		,TargetTbl.[RelStrat]=SourceTbl.[Column 60]
		,TargetTbl.[PoRelId]=SourceTbl.[Column 61]
		,TargetTbl.[RelStatus]=SourceTbl.[Column 62]
		,TargetTbl.[RelNotEffected]=SourceTbl.[Column 63]
		,TargetTbl.[ReportingCntry]=SourceTbl.[Column 64]
		,TargetTbl.[ReleaseDoc]=SourceTbl.[Column 65]
		,TargetTbl.[Address]=Case When SourceTbl.[Column 66] = ' ' Then Null Else SourceTbl.[Column 66] End
		,TargetTbl.[TaxDestCntry]=SourceTbl.[Column 67]
		,TargetTbl.[VatRegNbr]=SourceTbl.[Column 68]
		,TargetTbl.[ReasonCancel]=Case When SourceTbl.[Column 69] = ' ' Then Null Else SourceTbl.[Column 69] End
		,TargetTbl.[DocNbr]=Case When SourceTbl.[Column 70] = ' ' Then Null Else SourceTbl.[Column 70] End
		,TargetTbl.[CorrMiscProvisions]=SourceTbl.[Column 71]
		,TargetTbl.[Incomplete]=SourceTbl.[Column 72]
		,TargetTbl.[ProcState]=SourceTbl.[Column 73]
		,TargetTbl.[TtlValRelease]=Case When SourceTbl.[Column 74] = ' ' Then Null Else SourceTbl.[Column 74] End
		,TargetTbl.[Version]=Case When SourceTbl.[Column 75] = ' ' Then Null Else SourceTbl.[Column 75] End
		,TargetTbl.[ScmPo]=SourceTbl.[Column 76]
		,TargetTbl.[GrReasonCd]=SourceTbl.[Column 77]
		,TargetTbl.[IncompleteCat]=SourceTbl.[Column 78]
		,TargetTbl.[RetentionId]=SourceTbl.[Column 79]
		,TargetTbl.[RetentionPercent]=SourceTbl.[Column 80]
		,TargetTbl.[DownPmtId]=SourceTbl.[Column 81]
		,TargetTbl.[DownPmtPercent]=SourceTbl.[Column 82]
		,TargetTbl.[DownPmtAmt]=SourceTbl.[Column 83]
		,TargetTbl.[DueDtDownPay]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 84],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 84],5,0,'/'),8,0,'/') End
		,TargetTbl.[ProcessIdNbr]=Case When SourceTbl.[Column 85] = ' ' Then Null Else SourceTbl.[Column 85] End
		,TargetTbl.[ContractHierarchy]=SourceTbl.[Column 86]
		,TargetTbl.[ThreshValExists]=SourceTbl.[Column 87]
		,TargetTbl.[LegalContractNbr]=Case When SourceTbl.[Column 88] = ' ' Then Null Else SourceTbl.[Column 88] End
		,TargetTbl.[ContractName]=SourceTbl.[Column 89]
		,TargetTbl.[ReleasedOn]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 90],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 90],5,0,'/'),8,0,'/') End
		,TargetTbl.[ShipTyp]=SourceTbl.[Column 91]
		,TargetTbl.[HandoverLoc]=SourceTbl.[Column 92]
		,TargetTbl.[ShippingCond]=SourceTbl.[Column 93]
		,TargetTbl.[InteralKeyForceElement]=SourceTbl.[Column 94]
		,TargetTbl.[Counter]=Case When SourceTbl.[Column 95] = ' ' Then Null Else SourceTbl.[Column 95] End
		,TargetTbl.[RelocationId]=SourceTbl.[Column 96]
		,TargetTbl.[RelocationStep]=SourceTbl.[Column 97]
		,TargetTbl.[LogicalSys2]=SourceTbl.[Column 98]
		,TargetTbl.[RmaAuthVal]=SourceTbl.[Column 99]
		,TargetTbl.[Utilization]=SourceTbl.[Column 100]
		,TargetTbl.[ReturnsHeader]=SourceTbl.[Column 101]
		,TargetTbl.[FinalInvoiceInd]=SourceTbl.[Column 102]
		,TargetTbl.[ExcludeB2bPoUpdt]=SourceTbl.[Column 103]
		,TargetTbl.[EDICreateNbr]=SourceTbl.[Column 104]
		,TargetTbl.[EDIChangeNbr]=SourceTbl.[Column 105]
		,TargetTbl.[FaxEmailCreateNbr]=SourceTbl.[Column 106]
		,TargetTbl.[FaxEmailChangeNbr]=SourceTbl.[Column 107]
		,TargetTbl.[InterestIdic]=SourceTbl.[Column 108]
		,TargetTbl.[DocCat]=SourceTbl.[Column 109]
		,TargetTbl.[SameDlvryDt]=Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 110],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 110],5,0,'/'),8,0,'/') End
		,TargetTbl.[PlantAllItmRec]=SourceTbl.[Column 111]
		,TargetTbl.[FirmDealId]=SourceTbl.[Column 112]
		,TargetTbl.[TakeAccOfPrchgrp]=SourceTbl.[Column 113]
		,TargetTbl.[TakeAccPlant]=SourceTbl.[Column 114]
		,TargetTbl.[TakeAccContract]=SourceTbl.[Column 115]
		,TargetTbl.[TakeAccItmCat]=SourceTbl.[Column 116]
		,TargetTbl.[FixedDtPurchases]=SourceTbl.[Column 117]
		,TargetTbl.[ConsiderBudget]=SourceTbl.[Column 118]
		,TargetTbl.[AllocTableRelevance]=SourceTbl.[Column 119]
		,TargetTbl.[TakeAcctDlvryPeriod]=SourceTbl.[Column 120]
		,TargetTbl.[TakeAccDlvyDt]=SourceTbl.[Column 121]
		,TargetTbl.[IncludeVendorSub]=SourceTbl.[Column 122]
		,TargetTbl.[OTBCheckLevel]=SourceTbl.[Column 123]
		,TargetTbl.[OTBConditionTyp]=SourceTbl.[Column 124]
		,TargetTbl.[BudgetNbr]=SourceTbl.[Column 125]
		,TargetTbl.[RequiredBudget]=SourceTbl.[Column 126]
		,TargetTbl.[OTBCurr]=SourceTbl.[Column 127]
		,TargetTbl.[ReservedBudget]=SourceTbl.[Column 128]
		,TargetTbl.[SpecialRelease]=SourceTbl.[Column 129]
		,TargetTbl.[OTBReasonProfile]=SourceTbl.[Column 130]
		,TargetTbl.[BudgetTyp]=SourceTbl.[Column 131]
		,TargetTbl.[OTBStatus]=SourceTbl.[Column 132]
		,TargetTbl.[Reason]=SourceTbl.[Column 133]
		,TargetTbl.[TypOTBCheck]=SourceTbl.[Column 134]
		,TargetTbl.[OTBRelContract]=SourceTbl.[Column 135]
		,TargetTbl.[ContractIdLvl]=SourceTbl.[Column 136]
		,TargetTbl.[DistTrgtValItm]=SourceTbl.[Column 137]
WHEN NOT MATCHED BY TARGET AND SourceTbl.[Column 0] Is Not Null and SourceTbl.[Column 0] <> ' ' THEN
INSERT(
	[Client]
	,[PoNbr]
	,[CoCd]
	,[PoCat]
	,[PurReqDocType]
	,[ControlId]
	,[PurOrgData]
	,[Status]
	,[ChangedDt]
	,[CreatedBy]
	,[ItmNbrInterval]
	,[LastItmNbr]
	,[VenAccNbr]
	,[Language]
	,[PaytTerms]
	,[DiscDays1]
	,[DiscDays2]
	,[DiscDays3]
	,[DiscPct1]
	,[DiscPct2]
	,[PurchOrg]
	,[PurGrp]
	,[OrderCurr]
	,[ExchangeRate]
	,[ExchRateFixed]
	,[PoDt]
	,[ValidStartDt]
	,[ValidEndDt]
	,[AppClosingDt]
	,[BidSubmissionDeadline]
	,[BIdPeriodQuote]
	,[WarrantyStartDt]
	,[BidInvitationNbr]
	,[QuoteNbr]
	,[QuoteSubmissionDt]
	,[YourRef]
	,[SalesPersonResp]
	,[VenTeleNbr]
	,[SuppVendor]
	,[SoldToPartyId]
	,[Agreement]
	,[RejectionReason]
	,[CompleteDlvry]
	,[GrMessage]
	,[SupplyingPlant]
	,[ReceivedVendor]
	,[Incoterms1]
	,[Incoterms2]
	,[TargetVal]
	,[CollectiveNbr]
	,[DocCondNbr]
	,[CostingSheet]
	,[UpdateGrp]
	,[InvoicingParty]
	,[ForeignTradeDataNbr]
	,[OurReference]
	,[LogicalSys]
	,[SubItmNbr]
	,[DocTimeDepCond]
	,[RelGrp]
	,[RelStrat]
	,[PoRelId]
	,[RelStatus]
	,[RelNotEffected]
	,[ReportingCntry]
	,[ReleaseDoc]
	,[Address]
	,[TaxDestCntry]
	,[VatRegNbr]
	,[ReasonCancel]
	,[DocNbr]
	,[CorrMiscProvisions]
	,[Incomplete]
	,[ProcState]
	,[TtlValRelease]
	,[Version]
	,[ScmPo]
	,[GrReasonCd]
	,[IncompleteCat]
	,[RetentionId]
	,[RetentionPercent]
	,[DownPmtId]
	,[DownPmtPercent]
	,[DownPmtAmt]
	,[DueDtDownPay]
	,[ProcessIdNbr]
	,[ContractHierarchy]
	,[ThreshValExists]
	,[LegalContractNbr]
	,[ContractName]
	,[ReleasedOn]
	,[ShipTyp]
	,[HandoverLoc]
	,[ShippingCond]
	,[InteralKeyForceElement]
	,[Counter]
	,[RelocationId]
	,[RelocationStep]
	,[LogicalSys2]
	,[RmaAuthVal]
	,[Utilization]
	,[ReturnsHeader]
	,[FinalInvoiceInd]
	,[ExcludeB2bPoUpdt]
	,[EDICreateNbr]
	,[EDIChangeNbr]
	,[FaxEmailCreateNbr]
	,[FaxEmailChangeNbr]
	,[InterestIdic]
	,[DocCat]
	,[SameDlvryDt]
	,[PlantAllItmRec]
	,[FirmDealId]
	,[TakeAccOfPrchgrp]
	,[TakeAccPlant]
	,[TakeAccContract]
	,[TakeAccItmCat]
	,[FixedDtPurchases]
	,[ConsiderBudget]
	,[AllocTableRelevance]
	,[TakeAcctDlvryPeriod]
	,[TakeAccDlvyDt]
	,[IncludeVendorSub]
	,[OTBCheckLevel]
	,[OTBConditionTyp]
	,[BudgetNbr]
	,[RequiredBudget]
	,[OTBCurr]
	,[ReservedBudget]
	,[SpecialRelease]
	,[OTBReasonProfile]
	,[BudgetTyp]
	,[OTBStatus]
	,[Reason]
	,[TypOTBCheck]
	,[OTBRelContract]
	,[ContractIdLvl]
	,[DistTrgtValItm]
	)
VALUES
	(
	[Column 0]
	,[Column 1]
	,[Column 2]
	,[Column 3]
	,[Column 4]
	,[Column 5]
	,[Column 6]
	,[Column 7]
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 8],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 8],5,0,'/'),8,0,'/') End
	,[Column 9]
	,[Column 10]
	,[Column 11]
	,CASE WHEN TRY_CAST(SourceTbl.[Column 12] AS BIGINT) IS NULL AND LEN(SourceTbl.[Column 12])=5 THEN RIGHT(SourceTbl.[Column 12],4) WHEN TRY_CAST(SourceTbl.[Column 12] AS BIGINT) IS NOT NULL AND LEN(SourceTbl.[Column 12])>3 THEN CAST(SourceTbl.[Column 12] AS BIGINT) END
	,[Column 13]
	,[Column 14]
	,Replace(SourceTbl.[Column 15],'.','')
	,Replace(SourceTbl.[Column 16],'.','')
	,Replace(SourceTbl.[Column 17],'.','')
	,[Column 18]
	,[Column 19]
	,[Column 20]
	,[Column 21]
	,[Column 22]
	,[Column 23]
	,[Column 24]
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 25],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 25],5,0,'/'),8,0,'/') End
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 26],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 26],5,0,'/'),8,0,'/') End
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 27],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 27],5,0,'/'),8,0,'/') End
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 28],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 28],5,0,'/'),8,0,'/') End
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 29],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 29],5,0,'/'),8,0,'/') End
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 30],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 30],5,0,'/'),8,0,'/') End
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 31],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 31],5,0,'/'),8,0,'/') End
	,Case When SourceTbl.[Column 32] = ' ' Then Null Else SourceTbl.[Column 32] End
	,[Column 33]
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 34],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 34],5,0,'/'),8,0,'/') End
	,[Column 35]
	,[Column 36]
	,[Column 37]
	,[Column 38]
	,Case When SourceTbl.[Column 39] = ' ' Then Null Else SourceTbl.[Column 39] End
	,[Column 40]
	,[Column 41]
	,[Column 42]
	,[Column 43]
	,CASE WHEN ISNUMERIC(SourceTbl.[Column 44]) IS NULL THEN NULL ELSE SourceTbl.[Column 44] END
	,[Column 45]
	,[Column 46]
	,[Column 47]
	,[Column 48]
	,Case When SourceTbl.[Column 49] = ' ' Then Null Else SourceTbl.[Column 49] End
	,Case When SourceTbl.[Column 50] = ' ' Then Null Else SourceTbl.[Column 50] End
	,[Column 51]
	,[Column 52]
	,[Column 53]
	,Case When SourceTbl.[Column 54] = ' ' Then Null Else SourceTbl.[Column 54] End
	,[Column 55]
	,[Column 56]
	,[Column 57]
	,[Column 58]
	,[Column 59]
	,[Column 60]
	,[Column 61]
	,[Column 62]
	,[Column 63]
	,[Column 64]
	,[Column 65]
	,Case When SourceTbl.[Column 66] = ' ' Then Null Else SourceTbl.[Column 66] End
	,[Column 67]
	,[Column 68]
	,Case When SourceTbl.[Column 69] = ' ' Then Null Else SourceTbl.[Column 69] End
	,Case When SourceTbl.[Column 70] = ' ' Then Null Else SourceTbl.[Column 70] End
	,[Column 71]
	,[Column 72]
	,[Column 73]
	,Case When SourceTbl.[Column 74] = ' ' Then Null Else SourceTbl.[Column 74] End
	,Case When SourceTbl.[Column 75] = ' ' Then Null Else SourceTbl.[Column 75] End
	,[Column 76]
	,[Column 77]
	,[Column 78]
	,[Column 79]
	,[Column 80]
	,[Column 81]
	,[Column 82]
	,[Column 83]
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 84],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 84],5,0,'/'),8,0,'/') End
	,Case When SourceTbl.[Column 85] = ' ' Then Null Else SourceTbl.[Column 85] End
	,[Column 86]
	,[Column 87]
	,Case When SourceTbl.[Column 88] = ' ' Then Null Else SourceTbl.[Column 88] End
	,[Column 89]
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 90],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 90],5,0,'/'),8,0,'/') End
	,[Column 91]
	,[Column 92]
	,[Column 93]
	,[Column 94]
	,Case When SourceTbl.[Column 95] = ' ' Then Null Else SourceTbl.[Column 95] End
	,[Column 96]
	,[Column 97]
	,[Column 98]
	,[Column 99]
	,[Column 100]
	,[Column 101]
	,[Column 102]
	,[Column 103]
	,[Column 104]
	,[Column 105]
	,[Column 106]
	,[Column 107]
	,[Column 108]
	,[Column 109]
	,Case When TRY_CAST(STUFF(STUFF(SourceTbl.[Column 110],5,0,'/'),8,0,'/') as DATETIME2) IS Null THEN Null Else STUFF(STUFF(SourceTbl.[Column 110],5,0,'/'),8,0,'/') End
	,[Column 111]
	,[Column 112]
	,[Column 113]
	,[Column 114]
	,[Column 115]
	,[Column 116]
	,[Column 117]
	,[Column 118]
	,[Column 119]
	,[Column 120]
	,[Column 121]
	,[Column 122]
	,[Column 123]
	,[Column 124]
	,[Column 125]
	,[Column 126]
	,[Column 127]
	,[Column 128]
	,[Column 129]
	,[Column 130]
	,[Column 131]
	,[Column 132]
	,[Column 133]
	,[Column 134]
	,[Column 135]
	,[Column 136]
	,[Column 137]
	)
;


TRUNCATE TABLE ImportEkko

