USE NonHaImportTesting
GO

TRUNCATE TABLE SAP.dbo.Konp
Go

Insert Into SAP.dbo.Konp
(
	   [Client]
	  ,[NbrCondRecBatch]
      ,[SequNbrOfCond]
      ,[Application]
      ,[CondTyp]
      ,[TextNbr]
      ,[ScaleTyp]
      ,[ScaleBasis]
      ,[ScaleQty]
      ,[ScaleUom]
      ,[ScaleVal]
      ,[ScaleCurr]
      ,[CalcTyp]
      ,[RateNoScaleExists]
      ,[CondCurr]
      ,[PricingUnit]
      ,[CondUnitOfMeasure]
      ,[ScaleGrp]
      ,[NumForConv]
      ,[DenomForConv]
      ,[UnitOfMeasure]
      ,[LowerLimItm]
      ,[UpperLimitCondRate]
      ,[PlannedCondVal]
      ,[CumulativeGuaranteeDiscount]
      ,[CumulativeAccr]
      ,[CumCondCurr]
      ,[PlannedBasis]
      ,[Exclusion]
      ,[SoldToPartyId]
      ,[Vendor]
      ,[TaxCd]
      ,[DeleteId]
      ,[CondItmIndex]
      ,[MatRebateSettle]
      ,[Accruals]
      ,[Retroactive]
      ,[CondRecStatus]
      ,[Promotion]
      ,[SalesDeal]
      ,[SalesQuote]
      ,[AddValDays]
      ,[FixedValDt]
      ,[PayTerms]
      ,[MaxNbrSalesOrder]
      ,[MinCondBaseVal]
      ,[MaxCondBaseVal]
      ,[MaxCondVal]
      ,[IncrementScale]
      ,[PricingScale]
      ,[RelToPricing]
      ,[SalValIncVat]
      ,[Agreement]
      ,[WTaxCd]
      ,[ContractTyp]
      ,[ContractNbr]
      ,[FlowTyp]
      ,[MatrixMaint]
      ,[ReleaseStat]
      ,[StatusBvCA]
      ,[ContractTyp2]
      ,[ContractNbr2]
      ,[FlowTyp2]
)
Select 
[Column 0]
      ,[Column 1]
      ,[Column 2]
      ,[Column 3]
      ,[Column 4]
      ,[Column 5]
      ,[Column 6]
      ,[Column 7]
      ,[Column 8]
      ,[Column 9]
      ,[Column 10]
      ,[Column 11]
      ,[Column 12]
      ,[Column 13]
      ,[Column 14]
      ,[Column 15]= Replace([Column 15],'.','')
      ,[Column 16]
      ,[Column 17]
      ,[Column 18]= Replace([Column 15],'.','')
      ,[Column 19]= Replace([Column 15],'.','')
      ,[Column 20]
      ,[Column 21]
      ,[Column 22]
      ,[Column 23]
      ,[Column 24]
      ,[Column 25]
      ,[Column 26]
      ,[Column 27]
      ,[Column 28]
      ,[Column 29]
      ,[Column 30]
      ,[Column 31]
      ,[Column 32]
      ,[Column 33]
      ,[Column 34]
      ,[Column 35]
      ,[Column 36]
      ,[Column 37]
      ,[Column 38]
      ,[Column 39]
      ,[Column 40]
      ,[Column 41]
      ,Case When Try_Cast(STUFF(STUFF([Column 42],5,0,'/'),8,0,'/') as DATETIME2) IS NULL THEN Null 
Else STUFF(STUFF([Column 42],5,0,'/'),8,0,'/') End
      ,[Column 43]
      ,[Column 44]
      ,[Column 45]
      ,[Column 46]
      ,[Column 47]
      ,[Column 48]
      ,[Column 49]
      ,[Column 50]
      ,[Column 51]
      ,[Column 52]
      ,[Column 53]
      ,[Column 54]
      ,[Column 55]
      ,[Column 56]
      ,[Column 57]
      ,[Column 58]
      ,[Column 59]
      ,[Column 60]
      ,[Column 61]
      ,[Column 62]

From NonHaImportTesting.dbo.ImportKonp
Where [Column 0] Is Not Null and [Column 0] <> ' '

TRUNCATE TABLE NonHaImportTesting.dbo.ImportKonp