DROP TABLE sap.dbo.Ebew

CREATE TABLE sap.dbo.Ebew
(
Client varchar (5),
Material bigint,
ValArea int,
ValTyp varchar (12),
SpecialStk varchar (3),
SalesDocNbr bigint,
SalesDocItmNbr int,
TtlValStk decimal (13, 3),
ValTtlValStk money,
PriceControl varchar (3),
Map money,
StandardPrice money,
PriceUnitItm int,
ValClass int,
ValMap money,
TtlStkValPP decimal (13, 3),
TtlValPP money,
PriceCtrlPP varchar (3),
MapPP money,
StdPricePP money,
PriceUnitItmPP int,
ValClassPP varchar (6),
MapValPP money,
TtlStkPrevYr decimal (13, 3),
TtlValPrevYr money,
PriceCtrlPrevYr varchar (3),
MapPrevYr money,
StdPricePrevYr money,
PriceUnItmPrevYr int,
ValClassPrevYr varchar (6),
ValPrevYear money,
YearCurrPeriod int,
CurrPeriod int,
ValCat varchar (3),
PrevPrice money,
LastPriceChange datetime2,
FutPrice money,
ValidFrom datetime2,
[TimeStamp] datetime2,
FutPlandPrice money,
FutCostEst varchar (3),
CurrCostEst varchar (3),
PrevCostEst varchar (3),
ProdCostEstNbr bigint,
ValVarCostEstFut varchar (5),
ValVarCostEstStandard varchar (5),
ValVarCostEstPrev varchar (5),
CostingVersionFut int,
CostingVersionCurr int,
CostingVersionPrev int,
OriginGrp varchar (6),
OverheadGrp varchar (12),
PostingPeriod int,
CurrPeriodStandCostEst int,
PrevPeriod int,
FutFY int,
CurrFY int,
PrevFY int,
CostEstWQs varchar (3),
PrevPlndPrice money,
MatLedgerActive varchar (3),
PriceDetermine varchar (3),
CurrPlanPrice money,
TtlSpVal money,
MatOrigin varchar (3),
ValMargin decimal (6, 2),
FxdCurrPlanPrice money,
PrevPlndPriceFixed money,
FixedPortionFuturePlanPrice money,
CurrValStgy varchar (3),
PrevValStrat varchar (3),
FutValStrat varchar (3),
MbewRecAlreadyExists varchar (3),
VcVendor varchar (6)

);