USE SAP
GO

DROP TABLE SAP.dbo.Rseg

CREATE TABLE SAP.dbo.Rseg
	(
			Client varchar (5),
			AcctDocNbr bigint,
			FY int,
			AcctDocLineItmNbr int,
			PoNbr bigint ,
			PoItmNbr int,
			SeqNbrAccAss int,
			Material bigint,
			ValArea int,
			ValTyp varchar (12),
			CoCd varchar (6),
			Plant int,
			AmtDocCurr money,
			[Returns] varchar (3),
			TaxCd varchar (4),
			TaxJur varchar (17),
			SchedQty decimal (13, 3),
			PoOrderUnit varchar (5),
			QtyPoPriceUnit decimal (13, 3),
			PoPriceUnit varchar (5),
			TtlStkVal decimal (13, 3),
			StkPrevPP decimal (13, 3),
			BasUnit varchar (5),
			PoItmCat varchar (3),
			AcctAssignCat varchar (3),
			ValClass int,
			FinalInvoice varchar (3),
			UpdatePoHistId varchar (3),
			UpdatePoDlvryCost varchar (3),
			SubseqDbCrId varchar (3),
			BlockReasPrice varchar (3),
			BlockReasQty varchar (3),
			BlockReasDt varchar (3),
			BlockReasOpQty varchar (3),
			BlockReasProj varchar (3),
			ManBlockReason varchar (3),
			BlockReasItmAmt varchar (3),
			BlockQuality varchar (3),
			BlockReas varchar (6),
			ValString varchar (31),
			Reference varchar (3),
			BackPostingId money,
			DlvryCostItmVal varchar (6),
			CondTyp money,
			TtlVal money,
			TtlValPP varchar (3),
			LifoFifoRel float (53),
			RefDocNbr int,
			YearCurrentPeriod int,
			RefDocItm varchar (20),
			StkMat decimal (13, 3),
			InvDocQty decimal (13, 3),
			QtyInvoiceVend money,
			InvAmntFc varchar (3),
			VendorError varchar (4),
			ActivityCdGIT varchar (5),
			Region varchar (4),
			DistrTypEmployTax decimal (10),
			PackageNbr decimal (10),
			SvcLineNbr varchar (52),
			[Text] varchar (3),
			WOCashDiscountId varchar (3),
			CorrectionId varchar (3),
			Ok int,
			StepNbr int,
			CondCounter money,
			StockPost money,
			StockPostPrevPeriod money,
			StockPostPrevYr varchar (3),
			GrIrClearing varchar (12),
			Vendor varchar (18),
			BillOfLadingNbr varchar (3),
			UpdateMultiAcctAssmt varchar (4),
			ComplaintsReasonInvoice varchar (3),
			RetentionAmtDocCurr money,
			[Retention] decimal (5, 2),
			DueDt varchar (10),
			TaxReduction varchar (3),
			ExpenseRevenueAcct varchar (12),
			AgreeNbr varchar (12),
			AgreeItmNbr int,
			CentralContract varchar (12),
			CentralContractItm decimal (10),
			ItmCat varchar (3),
			ItmId decimal (10),
			BatchNbr varchar (12),
			ItmOrigin varchar (3),
			[Grouping] int,
			DiffInvoicingId varchar (3),
			DiffAmt money,
			CommRepricing varchar (3),
			InternalNbr decimal (10),
			MatDocItm int,
			StkSegment varchar (18)

	)