USE SAP
GO
DROP TABLE MARA

-- Values are =/= to SqlRelationships database
-- Order of columns matches Bob's file, not SAP

Create Table MARA(
	Client Varchar (3),
	Material Varchar (18),
	CreatedOn Datetime2,
	EnteredBy Varchar (12),
	LastChange Datetime2,
	ChangedBy Varchar (12),
	CompleteStatus Varchar (15),
	MaintStatus Varchar (15),
	ValuationTyp Varchar (1),
	MaterialTyp Varchar (4),
	IdustrySector Varchar (1),
	MaterialGrp Varchar (9),
	OldMatNbr Varchar (18),
	UnitOfMeasure Varchar (3),
	PoUnitMeasure Varchar (3),
	DocNbr Varchar (22),
	DocTyp Varchar (3),
	DocVersion Varchar (2),
	PageFormat Varchar (4),
	DocChangeNbr Varchar (6),
	PageNbr Varchar (3),
	NbrOfSheets Int,
	ProdInspMemo Varchar (18),
	PageFormatProdMemo Varchar (4),
	Size Varchar (32),
	IdStdDesc Varchar (18),
	LabOffice Varchar (3),
	PurchValKey Varchar (4),
	GrossWeight Decimal (13, 3),
	NetWeight Decimal (13, 3),
	WeightUnit Varchar (3),
	Volume Decimal (13, 3),
	VolumeUnitItm Varchar (3),
	ContainerReq Varchar (2),
	StkrCondItmions Varchar (2),
	TemperatureId Varchar (2),
	LowLevelCd Varchar (3),
	TransportationGrp Varchar (4),
	HazMatNbr Varchar (18),
	Division Varchar (2),
	SoldToPartyId Varchar (10),
	EanNbr Varchar (13),
	GrSlipsQty Decimal (13, 3),
	ProcureRule Varchar (1),
	SupplySource Varchar (1),
	Season Varchar (4),
	LabelTyp Varchar (2),
	LabelForm Varchar (2),
	FieldDeact Varchar (1),
	EanUpc Varchar (18),
	EanCat Varchar (2),
	Length Decimal (13, 3),
	Width Decimal (13, 3),
	Height Decimal (13, 3),
	UnitDemin Varchar (3),
	ProdHierarchy Varchar (18),
	NetChangeCstg Varchar (1),
	CadId1 Varchar (1),
	QmProcure Varchar (1),
	AllowedPkgWt Decimal (13, 3),
	UnitOfWeight Varchar (3),
	AllowedVolume Decimal (13, 3),
	VolumeUnit Varchar (3),
	ExcessWtTolerance Decimal (3, 1),
	ExcessVolTol Decimal (3, 1),
	VarOrderUnitItm Varchar (1),
	RevisionLevel Varchar (1),
	OriginOfConfig Varchar (1),
	BatchRequirementId Varchar (1),
	PackMatTyp Varchar (4),
	MaxLevel Decimal (3),
	StackingFactor Int,
	MatlGrpPackingMat Varchar (4),
	AuthGrp Varchar (4),
	AssignValidFrom Datetime2,
	ValidTo Datetime2,
	SeasonYear Varchar (4),
	PriceBandCat Varchar (2),
	WEmptiesBom Varchar (1),
	ExtMatGrp Varchar (18),
	Plant Varchar (18),
	MatCat Varchar (2),
	CoProduct Varchar (1),
	FollowUpMat Varchar (1),
	PrRefMatl Varchar (18),
	Plant1 Varchar (2),
	XDchainStatus Varchar (2),
	ValidFrom Datetime2,
	ValidFrom1 Datetime2,
	TaxClass Varchar (1),
	CatalogProfile Varchar (9),
	MinRemShelfLife Decimal (4),
	TtlShelfLife Decimal (4),
	StorPercent Decimal (3),
	ContentUnit Varchar (3),
	NetContents Decimal (13, 3),
	CompPriceUnitItm Decimal (5),
	LabelMatlGrp Varchar (18),
	GrossContents Decimal (13, 3),
	ConvMethodQty Varchar (1),
	IntObjNbr Int,
	EnviroRelevant Varchar (1),
	ProdAllocation Varchar (18),
	PricingProfile Varchar (1),
	DiscKindId Varchar (1),
	MfrPartNbr Varchar (40),
	Mfg Varchar (10),
	InternalMaterialNbr Varchar (18),
	MfrPartProfile Varchar (4),
	UnItmMeasUse Varchar (1),
	Rollout Varchar (2),
	DgIdProfile Varchar (3),
	HighlyViscousId Varchar (1),
	InBulkLiquidId Varchar (1),
	SerialLvl Varchar (1),
	Closed Varchar (1),
	BatchRecReqId Varchar (1),
	AssignEffVals Varchar (10),
	ThisFieldIsNotUsed Int,
	PeriodId Varchar (2),
	RoundingRule Varchar (2),
	ProdcomposItmion Varchar (4),
	GenItmCatGrp Varchar (4),
	LogVariants Varchar (4),
	MaterialLocked Varchar (4),
	ConfigManageRelv Varchar (1),
	AstmtListTyp Varchar (1),
	ExpDate Varchar (1),
	GlblTradeItmNbrVariant Varchar (2),
	GenericMat Varchar (18),
	RefMatPckg Varchar (18),
	GdsRelevant Varchar (1),
	OriginAccept Varchar (1),
	StandHuTyp Varchar (4),
	Pilferable Varchar (1),
	WhStkCond Varchar (2),
	WhMatGrp Varchar (4),
	HandlingId Varchar (4),
	HazSub Varchar (1),
	HandlingUnitTyp Varchar (4),
	VariableTw Varchar (5),
	MaxCapacity Decimal (15, 3),
	OverCapacTol Decimal (5, 1),
	MaxLength Decimal (15, 3),
	MaxPackWidth Decimal (15, 3),
	MaxHeight Decimal (15, 3),
	UnitOfMeasureMaxPackLength Varchar (5),
	CtryOfOrigin Varchar (5),
	MatFreightGrp Varchar (8),
	QuarantinePer Decimal (3),
	TimeUnItm Varchar (25),
	QualInspGrp Varchar (4),
	SerialNbrProfile Varchar (4),
	FormName Varchar (30),
	LogisticsUom Varchar (3),
	CwRelevant Varchar (1),
	CwProfile Varchar (2),
	CwToleranceGrp Varchar (9),
	LoadingUnitItm Int,
	LoadingUnitItmGrp Varchar (8),
	StructCatMatRelation Varchar (8),
	DsdGrping Varchar (6),
	TiltingAllowVSO Varchar (1),
	StackNotAllowVSO Varchar (1),
	BottomLayer Varchar (1),
	TopLayerVSO Varchar (3),
	StackFactorVSO Int,
	LoadWOPkMatVSO Varchar (5),
	OverhangDepthVSO Decimal (13, 3),
	OverhangWidthVSO Decimal (13, 3),
	MaxStackHghtVSO Decimal (13, 3),
	MinStackHghtVSO Decimal (13, 3),
	StackHghtToleranceVSO Decimal (13, 3),
	NbrMatClosedPkmVSO Decimal(13, 5),
	UnItmMeasureVSO Varchar (5),
	ClosedPackMatReqVSO Varchar (2),
	ConditionMgmt Varchar (1),
	ReturnCd Varchar (1),
	ReturnToLogLevel Varchar (1),
	Niin Varchar (9),
	FffClass Varchar (18),
	ChainNbr Varchar (18),
	DocStat Varchar (10),
	InternalCharNbrColorChar Int,
	InternalChar Int,
	InternalChar1 Int,
	ValColorVar Varchar (18),
	MainSize Varchar (18),
	SecondSize Varchar (18),
	CharValEvalPurp Varchar (18),
	CareCd Varchar (16),
	Brand Varchar (4),
	FiberCdTextile1 Varchar (3),
	PercShareFiber1 Int,
	FiberCdTextile2 Varchar (3),
	PercShareFiber2 Int,
	FiberCdTextile3 Varchar (3),
	PercShareFiber3 Int,
	FiberCdTextile4 Varchar (3),
	PercShareFiber4 Int,
	FiberCdTextile5 Varchar (3),
	PercShareFiber5 Int,
	FashionGrade Varchar (4),
	ToleranceTyp Varchar (4),
	CountingGrp Varchar (10),
	PackagingCd Varchar (10),
	DangGoodPckgStatus Varchar (10),
	GsaId Varchar (1),
	ElectronicPricing Varchar (1),
	AdjustProfile Varchar (3),
	IntelProperty Varchar (40),
	VarPriceAllowed Varchar (1),
	Medium Varchar (6),
	SparePrtClassCd Int,
	PhysCommodity Varchar (18),
	AnimalOrigin Varchar (1),
	TextileCompId Varchar (1),
	SegStructure Varchar (4),
	SegStgy Varchar (8),
	SegStatus Varchar (1),
	SegScope Varchar (1),
	SegRelevant Varchar (10),
	AnpCd Int,
	FshAttribute1 Varchar (10),
	FshAttribute2 Varchar (10),
	FshAttribute3 Varchar (6),
	SeasonUsage Varchar (1),
	SeasonActIm Varchar (1),
	MatConvId Varchar (2),
	PABC Varchar (3),
	ManualFlagInd Varchar (1),
	GreenNotGreen Varchar (18),
	WstsCd Varchar (5),
	RootMatOfMfr Varchar (40),
	ProdTyp Varchar (2),
	BatteryTyp Varchar (5),
	BatteryWeight Decimal (13, 3),
	OgSupplierName Varchar (35),
	DesignRegistrationFlag Varchar (5),
	Packing Varchar (3),
	AexPartClassFlag Varchar (1),
	AexBuyableStatFlag Varchar (1),
	ReachStatus Varchar (1),
	CeApplicabilIy Varchar (2),
	CeComment Varchar (100),
	CopyrightFee Varchar (1),
	WeeeCat Varchar (2),
	CcatsCommClassAutoTrackSys Varchar (10),
	LicenseException Varchar (5),
	BatteryCellCount Int,
	MoistureLevel Varchar (5),
	Description Varchar (40),
	DolbyStatus Varchar (1),
	HdmiStatus Varchar (1),
	WaiverStatus Varchar (40),
	AvnetLegacyPartNbr Varchar (40),
)