USE SAP 
GO

DROP TABLE VBFA

Create Table Vbfa(
Client varchar (5),
PrecedingDoc bigint,
PrecedingItm int,
SubsequentDoc bigint,
SubsequentItm int,
SubsDocCat varchar (3),
Qty decimal (15, 3),
UnitOfMeasure varchar (5),
RefVal decimal (15, 2),
OrderCurr varchar (7),
PrecDocCat varchar (3),
PosNegative varchar (3),
ConfId varchar (3),
CreateDt datetime2,
EntryTime time,
Material varchar (20),
MvmtTyp varchar (5),
ReqTyp varchar (4),
PlanningTyp varchar (3),
[Level] int,
WarehouseNbr varchar (5),
ChangedDt datetime2,
BillingCat varchar (3),
GrossWeight decimal (15, 3),
WeightUnit varchar (5),
Volume decimal (15, 3),
VolumeUnitItm varchar (5),
BillPlanNbr varchar (12),
BillPlanItm int,
RefQtySalesUnit decimal (30, 18),
RefQtyBaseUnit decimal (30, 18),
SalesUnitItm varchar (5),
Guaranteed varchar (18),
SpecialStkId varchar (3),
SpecStkNbr varchar (18),
InvMgmtActive varchar (3),
NetWeight decimal (13, 3),
LogSys varchar (12),
GoodsMvmtStat varchar (3),
ConvMethodQty varchar (3),
MatDocYear int,
PrecSdCatExt varchar (6),
SubsSdCatExt varchar (6)
)