USE SAP 
GO

DROP TABLE Mdkp



CREATE TABLE Mdkp

 (
Client varchar (5),
MrpListTyp varchar (4),
Material decimal (18),
Plant varchar (6),
PlanScenario int,
NbrMrpTable decimal (10),
MrpDt varchar (10),
ProcessMrpList varchar (3),
Exception1 varchar (3),
Exception2 varchar (3),
Exception3 varchar (3),
Exception4 varchar (3),
Exception5 varchar (3),
Exception6 varchar (3),
Exception7 varchar (3),
Exception8 varchar (3),
ProcessingId1 varchar (3),
ProcessingId2 varchar (3),
ProcessingId3 varchar (3),
MatTyp varchar (6),
BaseUnitMeas varchar (5),
LowLvlCd varchar (5),
ProcTyp varchar (3),
SpecProcTyp1 varchar (4),
SpecProcTyp2 varchar (3),
PlanProdPlant varchar (6),
MrpTyp varchar (4),
MrpProc varchar (3),
MrpCntrl varchar (5),
PlanCntrlr varchar (5),
PurchGrp varchar (5),
ReplenLeadTime int,
GrProcTime int,
ProcessTime int,
PlanTimeFence varchar (10),
ManTimeFence varchar (3),
LotSize varchar (4),
LotSizeProced varchar (3),
LotSizeId varchar (3),
NbrOfPeriods int,
SafetyStk decimal (13, 3),
ReorderPoint decimal (13, 3),
MaxStkLvl decimal (13, 3),
MinLotSize decimal (13, 3),
MaxLotSize decimal (13, 3),
FixLotSize decimal (13, 3),
RoundValPoQty decimal (13, 3),
PlantStk decimal (13, 3),
DoNotUse decimal (13, 3),
DoNotUse1 decimal (13, 3),
DoNotUse2 decimal (13, 3),
DoNotUse3 decimal (13, 3),
NegativeStk decimal (13, 3),
MessageId varchar (22),
MessageTyp varchar (3),
MessageNbr int,
MessageVar1 varchar (52),
MessageVar2 varchar (52),
MessageVar3 varchar (52),
MessageVar4 varchar (52),
MrpGrp varchar (6),
FyVariant varchar (4),
PlanCalendar varchar (5),
Requirements decimal (13, 3),
PlanCycle varchar (5),
RoundProf varchar (6),
StkDaySupply decimal (4, 1),
FirstRecDaySup decimal (4, 1),
DiscInd varchar (3),
EffOutDate varchar (10),
FollowUpMat varchar (20),
ExcGrpMRPList1 varchar (4),
ExcGrpMRPList2 varchar (4),
ExcGrpMRPList3 varchar (4),
ExcGrpMRPList4 varchar (4),
ExcGrpMRPList5 varchar (4),
ExcGrpMRPList6 varchar (4),
ExcGrpMRPList7 varchar (4),
ExcGrpMRPList8 varchar (4),
ProcessingDt varchar (10),
NewExceptions varchar (3),
RepetitiveMfg varchar (3),
PromotionId varchar (3),
SafetyTimeId varchar (3),
SafetyTime int,
JitId varchar (3),
ManFirmDt varchar (10),
StkConnectFlag varchar (3),
Abc varchar (3),
AggMrpList varchar (3),
GrpReq varchar (3),
CoverageProfile varchar (5),
StPerProfile varchar (5),
MrpDepReq varchar (3),
SecondReceiptDS decimal (4, 1),
BAdIActive varchar (3),
SegStatusMrp varchar (3),
HanaActive varchar (3),

PRIMARY KEY (Client, MrpListTyp, Material, Plant, PlanScenario)
)