USE SAP
GO

DROP TABLE VBRK

CREATE TABLE VBRK(
Client varchar (4),
SalesDocNbr bigint,
BillTyp varchar (5),
BillingCat varchar (2),
SalesDocCat varchar (2),
SalesDocCurr varchar (6),
SalesOrg varchar (5),
DistrChannel varchar (3),
CostingSheet varchar (7),
DocCondNbr varchar (11),
ShipCond varchar (3),
BillingDtIndexPrint datetime2,
AcctDocNbr varchar (11),
FY int,
PostingPeriod int,
PriceGrp varchar (3),
TechFeeServ varchar (3),
SalesDistrict varchar (7),
PriceList varchar (3),
IncotermsPart1 varchar (4),
IncotermsPart2 varchar (29),
ExportId varchar (2),
PostingStatus varchar (2),
SubsInvProcess varchar (2),
ExchRateAcct decimal (9, 5),
SetExchangeRate varchar (2),
AddValDays int,
FixedValDt datetime2,
PaytTerms varchar (5),
PymtMethod varchar (2),
AcctAssignGrpCust varchar (3),
DestCountry varchar (4),
Region varchar (4),
CountyCd varchar (4),
CityCd varchar (5),
CoCd varchar (5),
TaxClass1Cust varchar (2),
TaxClass2Cust varchar (2),
TaxClass3Cust varchar (2),
TaxClass4Cust varchar (2),
TaxClass5Cust varchar (2),
TaxClass6Cust varchar (2),
TaxClass7Cust varchar (2),
TaxClass8Cust varchar (2),
TaxClass9Cust varchar (2),
NetVal money,
CombCriteriaBillDoc varchar (41),
EnteredBy varchar (13),
EntryTime datetime2,
CreatedOn datetime2,
UpdateGrp varchar (7),
Payer varchar (11),
SoldToParty varchar (11),
DunningArea varchar (3),
StatsCurr varchar (6),
ForeignTradeDataNbr varchar (11),
VatRegNbr varchar (21),
ChangeDtOrderMaster datetime2,
CancelBillDoc varchar (11),
Agreement varchar (11),
InvListTyp varchar (5),
BillingDtInvoiceList datetime2,
ExchRateTyp varchar (5),
DunningKey varchar (2),
DunnBlock varchar (2),
Division varchar (3),
CreditCntrlArea varchar (5),
CreditAcct varchar (11),
CurrKeyCreditCntrlArea varchar (6),
ExchangeRateBillingDocRate decimal (9, 5),
HierTypPricing varchar (2),
CustPoNbr varchar (41),
TradingPartnerId varchar (21),
AccrualBillTyp varchar (5),
Application varchar (3),
TaxDepartCity varchar (4),
OriginSalesTax varchar (4),
TaxDestCntry varchar (4),
RefDocNbr varchar (31),
AssignmentNbr varchar (19),
TaxAmount money,
LogicalSystem varchar (11),
BillDocCancel varchar (6),
EuTriangDealId varchar (11),
PaymCardPlanNbr varchar (11),
FinanceDocNbr bigint,
TaxTyp varchar (11),
TranslationDt datetime2,
CurrKeyLetterCredit varchar (6),
ExchRateLetterCredit decimal (9, 5),
PymtRef varchar (31),
PartBankTyp varchar (5),
NbrOfPages int,
BusPlace varchar (5),
ContractAcct varchar (13),
AddFinanStatus varchar (2),
CharacterField12 varchar (13),
BillingId varchar (2),
RefSpecContract varchar (21),
SourceSystem varchar (11),
CrmBillCat varchar (2),
ReversalReason varchar (3),
SalesDocCatExt varchar (5),
DpcRelvFlag varchar (2),
ManDtRef varchar (36),
PmtTyp varchar (2),
SepaRelevantSEPON varchar (2),
SepaRelevantMNDVG varchar (2),
PaymtMethod varchar (3),
SalesOrderSpecPymt varchar (11),
SpecProcessingId varchar (5),
InvFlag varchar (36),


)