USE SAP 
GO 

DROP TABLE Vbkd

CREATE TABLE Vbkd(
Client  varchar (5),
SalesDocNbr varchar (12),
SalesDocItmNbr int,
PriceGrp varchar (4),
TechFeeServ varchar (4),
SalesDistrict varchar (8),
PriceList varchar (4),
Incoterms1 varchar (5),
Incoterms2 varchar (30),
OrderComboId varchar (3),
InvoicingDts varchar (4),
InvListSched varchar (4),
SubsInvProcess varchar (3),
ExchRateAcct decimal (9, 5),
AddValDays int,
FixedValDt datetime2,
PaytTerms varchar (6),
PymtMethod varchar (3),
AcctAssignGrpCust varchar (4),
ExchangeRate4 decimal (9, 5),
PricingDt datetime2,
BillingDtIdexPrint datetime2,
ServRenderedDt datetime2,
FY int,
PostingPeriod int,
ExchRateStat decimal (9, 5),
DunningKey varchar (3),
DunnBlock varchar (3),
BillPlanNbr varchar (12),
Promotion varchar (12),
PaymGuarProc varchar (8),
FinanceDocNbr varchar (12),
TaxTyp varchar (4),
Reason0Vat varchar (3),
Region varchar (5),
ActivityCdGIT varchar (4),
DistrTypEmployeTax varchar (4),
TaxRelClass varchar (12),
DepartmentNbr varchar (6),
RecvPoint varchar (27),
BSTKD varchar (44),
CustPoDt datetime2,
CustPoTyp varchar (10),
YourRef varchar (17),
ShipPartyPoNbr varchar (37),
ShipToPartyPoDt datetime2,
ShipPartyPoTyp varchar (10),
ShipPartyChar varchar (14),
PoItmem varchar (8),
TransDt3 datetime2,
TransDt2 datetime2,
ConditionGrp1 varchar (10),
ConditionGrp2 varchar (10),
ConditionGrp3 varchar (10),
ConditionGrp4 varchar (4),
ConditionGrp5 varchar (10),
ContractCurr varchar (10),
ExchangeRate decimal (9, 5),
CurrKeyLetterCredit varchar (9),
ExchRateLetterCredit decimal (9, 5),
DepreciationPercent decimal (8, 2),
InflationIdex varchar (9),
IdexBaseDt datetime2,
CustPoNbrMatchCd varchar (44),
AgreedDlvryTime varchar (15),
DynamicItmProcessProf varchar (17),
AcctId varchar (6),
BillForm varchar (4),
RevRecognition varchar (10),
AccPeriodStart varchar (9),
ShipTyp varchar (4),
MeansTransTyp varchar (6),
MeansTrans varchar (20),
SpecProcessing varchar (6),
[Catalog] varchar (12),
FunctionArea varchar (18),
PodRelevant varchar (3),
GenProjPlanGUID varchar (18),
ContractAcct varchar (14),
BillingPlanNbr varchar (12),
BillingPlanItm int,
RevenueDist varchar (3),
RevenueEvent varchar (8),
RevenueAcctTyp varchar (12),
RefSpecContract varchar (22),
PerOfPerfStart datetime2,
PerOfPerfEnd datetime2,
LstCstCd varchar (10),
FormTyp1 varchar (10),
FormTyp2 varchar (10),
ControlCd varchar (18),
AbbvComplaintReason varchar (10),
ManDtRef varchar (37),
PmtTyp varchar (3),
SepaRelevant1 varchar (3),
SepaRelevant2 varchar (3),
BufferTyp varchar (43)
)

