Use sap
Go

Drop Table sap.dbo.Likp

Create Table sap.dbo.Likp 
(
Client varchar (4),
SalesDocNbr varchar (11),
CreatedBy varchar (13),
EntryTime nvarchar (15),
CreatedOn nvarchar (27),
SalesDistrict varchar (7),
ShipPoint varchar (5),
SalesOrg varchar (5),
DlvryTypLFART varchar (5),
CompleteDlvry varchar (2),
OrderComboId varchar (2),
GoodIssDt nvarchar (27),
LoadingDt nvarchar (27),
TransportPlanDt nvarchar (27),
DlvryDt nvarchar (27),
PickDt nvarchar (27),
UnloadingPoint varchar (26),
Incoterms1 varchar (4),
Incoterms2 varchar (29),
ExportId varchar (2),
[Route] varchar (7),
BillBlockSalesDoc varchar (3),
DlvryBlock varchar (3),
SalesDocCat varchar (2),
FactoryCal varchar (3),
MeansTransQual varchar (2),
MeansTranspGrp varchar (3),
DlvryPrior int,
ShipCond varchar (3),
ShipToPartyId varchar (11),
SoldToPartyId varchar (11),
TechFeeServ varchar (3),
WaitTimeClass numeric (3, 2),
WaitTimeSurcharge numeric (3),
TtlWeight numeric (15, 3),
NetWeight numeric (15, 3),
WeightUnit varchar (4),
Volume numeric (15, 3),
VolumeUnitItm varchar (4),
NbrOfPackages int,
PickedItmLoc varchar (21),
TimeOfDlvry nvarchar (15),
WeightGrpDlvry varchar (5),
LoadingPoint varchar (3),
TransGrp varchar (5),
DlvryBillType varchar (5),
BillingDtIdexPrint nvarchar (27),
InvoicingDts varchar (3),
RouteA varchar (7),
UpdateGrp varchar (7),
CostingSheet varchar (7),
DocCondNbr varchar (11),
SalesDocCurr varchar (6),
SalesOffice varchar (5),
TtlProcTime numeric (6, 2),
CombCriteriaDlvry varchar (41),
DistDlvry varchar (36),
CommNbr varchar (6),
StatsCurr varchar (6),
ExchRateStat numeric (9, 5),
ForeignTradeDataNbr varchar (11),
ChangedBy varchar (13),
ChangedOn nvarchar (27),
WarehouseNbr varchar (4),
IdDlvrySplit varchar (2),
InterBillSalesOrg varchar (5),
InterBillDistrChannel varchar (3),
InterBillDivIv varchar (3),
InterBillTyp varchar (5),
InterBillDt varchar (3),
BillingDtInterBill nvarchar (27),
InterBillCustNbr varchar (11),
CreditCntrllArea varchar (5),
CreditAcct varchar (11),
CustCredGrp varchar (5),
CredRepGrp varchar (4),
RiskCat varchar (4),
CurrKeyCreditCtrlArea varchar (6),
CreditValDoc money,
BillLading varchar (36),
Vendor varchar (11),
MeansTransTyp varchar (5),
MeansTransId varchar (21),
DocReleaseDt nvarchar (27),
NextDt nvarchar (27),
GrSlipNbr varchar (11),
DocDt nvarchar (27),
GoodsMvmtDt nvarchar (27),
ShipBlockReason varchar (3),
IdTransSys varchar (6),
ExtDlvry varchar (36),
OrderNbr varchar (13),
SearchProcedDeterm varchar (7),
CorrDlvry varchar (2),
ShipPriceProcedure varchar (7),
DocCond varchar (11),
NetVal money,
RouteSched varchar (11),
ReceivingPlant varchar (5),
FinanceDocNbr varchar (11),
PaymGuarProc varchar (7),
PickingTime nvarchar (15),
TransPlanTime nvarchar (15),
LoadingTime nvarchar (15),
GoodsIssTime nvarchar (15),
DoorForWhse varchar (4),
StagingArea varchar (11),
CurrKeyLetterCredit varchar (6),
ExchRateLetterCredit numeric (9, 5),
DepreciationPercent numeric (5, 2),
DgMgmtProfile varchar (4),
RefDocNbr varchar (26),
LIKPVBLENkey varchar (23),
TSegmentExists varchar (2),
GrpTimeDelivery varchar (11),
DelTimeZone varchar (7),
RecTimeZone varchar (7),
ContainsDanGoods varchar (2),
DistDlvryOrigSys varchar (11),
IdGoodsMvmt varchar (2),
StatDecntrlWhse1 varchar (2),
TransCd1 varchar (21),
ShipTyp varchar (3),
MeansTrans varchar (19),
SpecProcessing varchar (5),
TradingPartnerID varchar (7),
CalcOfValOpen varchar (2),
AutoCreateTRGen varchar (2),
SupplyArea varchar (11),
DlvryTypFOLAR varchar (5),
PodDt nvarchar (27),
ConfTime nvarchar (15),
NbrDlvryItmPredSys int,
InPlantStatus varchar (2),
DocDeleteId varchar (2),
LocSeq varchar (4),
DelConfStat varchar (2),
ShipInfoStat varchar (2),
RetAsnCanc varchar (2),
GiTime nvarchar (15),
TimeZone varchar (7),
StatDecntrlWhse varchar (2),
ScenarioLogisticEx varchar (2),
OriginSysTyp varchar (2),
ChangerSysTyp varchar (2),
GeoRoute varchar (11),
ChgIdRoute varchar (2),
ChangeId varchar (2),
GdsTrafficTyp varchar (3),
GtsRouteCd varchar (11),
RlsTimeStamp numeric (15),
MsrmntUnitSys varchar (11),
InvBfGi varchar (2),
QiStatus varchar (2),
Redirected varchar (2),
StorStatus varchar (2),
TypExtIdent varchar (2),
MeansOfTrans varchar (11),
ProNbr varchar (36),
Akkreditiv varchar (17),
BillingId varchar (9),
PrintProfile varchar (11),
AdvReturns varchar (3),
ConfirmationNbr int,
StorLocChange varchar (3),
ControlKey varchar (6),
DlvrySplitId varchar (2),
DlvryVersion int,
HandoverLoc varchar (11),
HandoverDt nvarchar (27),
HandoverTime varchar (3),
HandoverLocTimeZone varchar (11),
LoadingUnitItm int,
NbrCat1 int,
NbrCat2 int,
NbrCat3 int,
NbrCat4 int,
SequenceNbr int,
InboundDlyGrp varchar (36),
ShcCiiInstruct varchar (6),
ItarMat varchar (7)
)