Drop Table sap.dbo.Marc;

CREATE TABLE sap.dbo.Marc
(
Client varchar (5),
Material bigint,
Plant int,
MaintStatus varchar (17),
ValTyp varchar (3),
ValCat varchar (3),
BatchId varchar (3),
PSMatStat varchar (4),
ValidFrom datetime2,
AbcId varchar (3),
CriticalPart varchar (3),
PurGrp varchar (5),
UnitOfIssue int,
MatMrpProf varchar (6),
MrpTyp varchar (4),
MrpCtrllrMatPlan varchar (5),
MrpCtrllrBuyer varchar (3),
PlanDlvryTime int,
GrProcTime int,
PeriodId varchar (3),
AssemblyScrapPercent decimal (5, 2),
LotSize varchar (4),
ProcTyp varchar (3),
SpecProcTyp varchar (4),
ReOrderPoint decimal (13, 3),
SafetyStk decimal (13, 3),
MinLotQty decimal (13, 3),
MaxLotQty decimal (13, 3),
FixedLotSize decimal (13, 3),
RoundingVal decimal (13, 3),
MaxStkLvl decimal (13, 3),
OrderingCosts money,
IdivColl varchar (3),
StorCostsId varchar (3),
SelectionMethod varchar (3),
DiscontinId varchar (3),
EffOutDt datetime2,
FollowUpMat varchar (20),
ReqGrp varchar (3),
MixedMrp varchar (3),
SchedMarginKeyFloats varchar (5),
AutomFixPlanOrders varchar (3),
ProdOrderReleaseId varchar (3),
Backflush varchar (3),
ProdSupervisor varchar (5),
ProcessTime decimal (5, 2),
SetupTime decimal (5, 2),
Interoperation decimal (5, 2),
BaseQty decimal (13, 3),
InHouseProdTime int,
MaxStorage int,
TimeUnitMaxStoragePeriod int,
WithdrawlProdBin varchar (3),
RoughCutPlanId varchar (3),
OverDlvryTol decimal (3, 1),
UnlimitedDlvryId varchar (3),
UnderDlvryTol decimal (3, 1),
TtlReplenLTime int,
ReplacemtPart varchar (3),
Surcharge decimal (5, 2),
StateOfMfg varchar (4),
PostInspectStk varchar (3),
[Sample] decimal (3, 1),
Quarantine int,
QmControlKey varchar (51),
MeanInspDur int,
InspPlanId varchar (3),
DocReq varchar (3),
ActiveSubst int,
InspectInterval int,
NextInspection datetime2,
StkTransfer decimal (13, 3),
LoadingGrp varchar (6),
BatchReqId varchar (3),
QuotaArrUsage varchar (3),
SvcLevel decimal (3, 1),
SplittingId varchar (3),
PlanVersion varchar (4),
ObjectTyp varchar (4),
ObjectId int,
AvailCheck varchar (4),
FYVariant varchar (4),
CorrectionFactors varchar (3),
ShipSetupTime decimal (5, 2),
BaseQtyCapPlanShip decimal (13, 3),
ProcTime decimal (5, 2),
Deactivated varchar (6),
SupplySource varchar (3),
AutoPoAllocId varchar (3),
SourceList varchar (3),
CommImpCd bigint,
CtryOfOrigin varchar (5),
RegOfOrigin varchar (5),
CommCdUnit int,
ExpImportGrp varchar (6),
ProfItmCenter bigint,
StkInTransItm decimal (13, 3),
PlanCalendar varchar (5),
RepetitiveMfg varchar (3),
PlanTimeFence int,
ConsumptionMode varchar (3),
BckwdConsPer int,
FwdConsPer int,
VersionId varchar (3),
BomAlt varchar (4),
BomUsage varchar (3),
Grp varchar (51),
GrpCounter varchar (4),
CostingLotSize decimal (13, 3),
SpecProcTypCost varchar (4),
ProdUnit int,
ProdStorLoc varchar (6),
MrpGrp varchar (6),
CompScrap decimal (5, 2),
CertificateTyp varchar (6),
InspSetup varchar (3),
TaktTime int,
CoverageProf varchar (5),
FieldName varchar (12),
CycleCountPhysInvId varchar (3),
VarianceKey varchar (8),
SerialNbrProfile varchar (6),
IntObjNbrConfig bigint,
ConfigMat varchar (20),
RemProfile varchar (6),
NegStks varchar (3),
TargetQmSys varchar (6),
PlanCycle varchar (5),
RoundingProfile varchar (6),
RefMatCons varchar (20),
RefPlant varchar (6),
DtTo datetime2,
Multiplier decimal (4, 2),
AutomReset varchar (3),
Preference varchar (3),
ExemptCert varchar (3),
ExemptCertNbr int,
ExemptCertId datetime2,
VendOrderId varchar (3),
VendorDeclDt datetime2,
MilitaryGoodsId varchar (3),
IRSSvcLevel varchar (3),
CoProduct varchar (3),
PlanStratGrp varchar (4),
IntObjNbrConfigMatPlan bigint,
StorLocEp varchar (6),
BulkMaterial varchar (3),
CcIdFixed varchar (3),
StkDetermGrp int,
QmMatAuth varchar (8),
AdjustmtPeriod decimal (3),
TaskListTyp varchar (3),
UomGrpUOMGR varchar (5),
ConvGrp varchar (6),
AirBuoyFact decimal (2, 1),
ProdProfile varchar (8),
SafetyTimeId int,
SafetyTime int,
ActionControl varchar (4),
EnterBatch int,
UomGrp varchar (6),
MatFreightGrp varchar (51),
StkTransSvPltToPlt money,
StInTransSp money,
SmthPromCons varchar (3),
ProdVersionCost varchar (6),
FixedPriceCoProd varchar (3),
LogisticsGrp varchar (6),
DistProf varchar (5),
TiedEmptiesStk decimal (13, 3),
SlsValTiedEmpt money,
MatCFOPCat varchar (4),
EuProdListNbr bigint,
CapProdGrp varchar (8),
CasNbrPharm bigint,
ProdComNbr int,
ControlCd varchar (18),
ItmRelvJITDlvrySchedId varchar (3),
MatGrp varchar (22),
ProposedSupplyArea varchar (12),
FairShareRule varchar (4),
PushDistId varchar (3),
DeployHorizonDays int,
MinLotSize decimal (13, 3),
MaxLotSize decimal (13, 3),
FixLotSize decimal (13, 3),
LotSizeIncr decimal (13, 3),
ThisFieldIsNotUsed int,
ConvTypProdFig varchar (4),
StPeriodProfile varchar (5),
MrpDepReqmts varchar (3),
MrpAreaExists varchar (3),
CrossProject varchar (3),
OverallProfile varchar (8),
MatRelevantAPOId int,
MardhRecAlreadyExists varchar (3),
CurrentPeriod int,
YearCurrentPeriod int,
MinSafetyStk decimal (13, 3),
DoNotCost varchar (3),
PutawayStkRmvl varchar (3),
ObjMgmtId varchar (3),
ObjRefMat varchar (20),
ValGrBlockStk decimal (13, 3),
PackGrpVSO varchar (3),
PickLineVSO varchar (12),
MatNbrPickMatVeVSO varchar (3),
PickPkmLengthVSO decimal (3, 1),
ConsignControl varchar (3),
GiProcTime varchar (3),
AcrossPurGrp varchar (3),
DeterSchema int,
MinTargetRange varchar (3),
MaxTargetRange varchar (3),
TargetStk varchar (10),
IuidRelev decimal (3, 1),
IuidTyp varchar (51),
ExtAllocationUii varchar (3),
PercentTolPlus decimal (13, 3),
PercentTolMinus decimal (13, 3),
SegStgy varchar (20),
SegStatusMrp varchar (5),
SegScope varchar (20),
StkSortMethod varchar (3),
ConsPrior varchar (3),
DiscreteBatchNbr int,
StkProtId varchar (3),
OrderAllocRun varchar (4),
SeasonActItm int,
PABC varchar (5),
ManualFlagId varchar (3),
MatReserveLevel varchar (5),
MinOrdQtySupplier decimal (13, 3),
RohsLevel varchar (4),
GreenProdId varchar (4),
SupplierCancelWId varchar (5),
SupplierLeadTime int,
VendorEdiLeadTime int,
LeadTimeOverrideFlag varchar (3),
AvnABCInd varchar (5),
RunRate varchar (11),
BookLeadTime int,
DaysOfSupply int,
StkProfile varchar (5),

PRIMARY KEY CLUSTERED 
(
	[Client] ASC,
	[Material] ASC,
	[Plant] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
