USE [SAP]
GO

/****** Object:  Table [dbo].[Knvv]    Script Date: 11/29/2017 10:58:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Knvv](
	[Client] [varchar](3) NULL,
	[CustNbr] [varchar](10) NULL,
	[SalesOrg] [varchar](4) NULL,
	[DistrChannel] [varchar](2) NULL,
	[Division] [varchar](2) NULL,
	[EnteredBy] [varchar](12) NULL,
	[CreatedOn] [datetime2](7) NULL,
	[AuthorizationGrp] [varchar](4) NULL,
	[CentralDeletionFlagForMasterRecord] [varchar](1) NULL,
	[MaterialStatisticsGrp] [varchar](1) NULL,
	[CentralOrderBlockForCust] [varchar](2) NULL,
	[CustPriceProcedure] [varchar](1) NULL,
	[TechnicalFeeForSvc] [varchar](2) NULL,
	[SalesDistrict] [varchar](6) NULL,
	[PriceGrpCust] [varchar](2) NULL,
	[PriceListType] [varchar](2) NULL,
	[SalesProb] [int] NULL,
	[IncotermsPart1] [varchar](3) NULL,
	[IncotermsPart2] [varchar](28) NULL,
	[CentralDeliveryBlockForTheCust] [varchar](2) NULL,
	[CompleteDeliveryDefinedForEachSalesOrder] [varchar](1) NULL,
	[MaxNbrPartDelAllPerItm] [int] NULL,
	[PartDelItmLvl] [varchar](1) NULL,
	[OrderComboId] [varchar](1) NULL,
	[BatchSplitAll] [varchar](1) NULL,
	[DeliveryPriority] [int] NULL,
	[AccountNbrAtCust] [varchar](12) NULL,
	[ShippingConditions] [varchar](2) NULL,
	[CentralBillingBlockForCust] [varchar](2) NULL,
	[ManualInvoiceMantenance] [varchar](1) NULL,
	[InvoiceDtsCalendarId] [varchar](2) NULL,
	[InvoiceListSchedule] [varchar](2) NULL,
	[CostEstimateInd] [varchar](1) NULL,
	[CostEstimateLimit] [decimal](13, 2) NULL,
	[Currency] [varchar](10) NULL,
	[CustClassABC] [varchar](2) NULL,
	[AcctAssignmentGrpThisCust] [varchar](2) NULL,
	[PmtKeyTerms] [varchar](4) NULL,
	[DlvryPlant] [varchar](4) NULL,
	[SaleGrp] [varchar](3) NULL,
	[SalesOffice] [varchar](4) NULL,
	[ItmProposal] [varchar](10) NULL,
	[CustGrp1] [varchar](3) NULL,
	[CustGrp2] [varchar](3) NULL,
	[CustGrp3] [varchar](3) NULL,
	[CustGrp4] [varchar](3) NULL,
	[CustGrp5] [varchar](3) NULL,
	[Rebate] [varchar](1) NULL,
	[RebateIndex] [datetime2](7) NULL,
	[ExchangeRateType2] [varchar](4) NULL,
	[PriceDetermin] [varchar](1) NULL,
	[NcnrFlag] [varchar](1) NULL,
	[LiquidtFlag] [varchar](1) NULL,
	[CustomProduct] [varchar](1) NULL,
	[SoftwareLicenseRequired] [varchar](1) NULL,
	[NdaRequired] [varchar](1) NULL,
	[DownloadableFlag] [varchar](1) NULL,
	[DualMarkingId] [varchar](1) NULL,
	[WaiverRequired] [varchar](1) NULL,
	[GlobalInventory] [varchar](1) NULL,
	[NaftaFlag] [varchar](1) NULL,
	[CustPayGuaranteeProcedure] [varchar](4) NULL,
	[CreditControlArea] [varchar](4) NULL,
	[CentralSalesBlockForCust] [varchar](2) NULL,
	[RoundingOff] [varchar](1) NULL,
	[AgencyBusInd] [varchar](1) NULL,
	[UntMeasGrp] [varchar](4) NULL,
	[OvrTolLmt] [decimal](3, 1) NULL,
	[UndTolLmt] [decimal](3, 1) NULL,
	[UnlOvrAll] [varchar](1) NULL,
	[CustProcedureProdProposal] [varchar](2) NULL,
	[RelevantPODProcessing] [varchar](1) NULL,
	[PODConfirmTimeframe] [decimal](11, 0) NULL,
	[BudgetaryLedgerId] [varchar](1) NULL,
	[CarrierNotification] [varchar](1) NULL,
	[PurposeCompleteInd] [varchar](1) NULL,
	[DepositOnEmpties] [varchar](1) NULL,
	[EmptiesUpdtInd] [varchar](1) NULL,
	[ShipWindowEarly] [int] NULL,
	[ShipWindowLate] [int] NULL,
	[CutoffWeight] [int] NULL,
	[FreightCdUnderCutoff] [varchar](1) NULL,
	[FreightAcctUnderCutoff] [varchar](12) NULL,
	[ShippingServiceLvlOverCutoff] [varchar](3) NULL,
	[FreightCdOverCutoff] [varchar](1) NULL,
	[FreightAcctOverCutoff] [varchar](12) NULL,
	[SingleLotDtCd] [varchar](1) NULL,
	[MaxDtCdAging] [int] NULL,
	[FreightConsolidation] [varchar](1) NULL,
	[Segment] [varchar](2) NULL,
	[AcctTyp] [varchar](1) NULL,
	[BillSpecialHandling] [varchar](1) NULL,
	[RegistrationMatchHigher] [varchar](1) NULL,
	[PayTermsException] [varchar](4) NULL,
	[FreightOnBoard] [varchar](2) NULL,
	[CustInspect] [varchar](6) NULL,
	[InvoiceFlag] [varchar](1) NULL,
	[XilinxSoldTo] [varchar](10) NULL,
	[XilinxShipTo] [varchar](30) NULL,
	[XilinxHubID] [varchar](10) NULL,
	[ExemptFromATPOver] [varchar](1) NULL,
	[SHC] [varchar](5) NULL,
	[MinBusUnit] [int] NULL,
	[TechFee] [varchar](15) NULL
) ON [PRIMARY]

GO


