USE SAP
GO

DROP TABLE Stpo

CREATE TABLE Stpo
(

Client varchar (6),
BomCat varchar (4),
Bom varchar (11),
BomItmNodeNbr int,
InternalCounter int,
ValidFromDt varchar (11),
TechStatFrom varchar (15),
ChangeNbr bigint,
DeletionId varchar (4),
PreviousNode int,
PrevItmCount int,
RecOrderCreatedOn varchar (11),
CreatedBy varchar (15),
CreatedOnAEDAT varchar (11),
CreatedByAENAM varchar (15),
BOMComp bigint,
Plant varchar (7),
ItmCat varchar (4),
SalesDocItmNbr varchar (7),
SortString varchar (13),
UnitOfMeasure varchar (6),
CompQty varchar (15),
QtyIsFixed varchar (4),
CompScrapPercent varchar (6),
OperationScrap varchar (6),
NetId varchar (4),
BulkMat varchar (4),
MatProvId varchar (4),
SparePartId varchar (4),
Sales varchar (4),
Production varchar (4),
PlantMaintId varchar (4),
CostingRelevncy varchar (4),
Engineering varchar (4),
HlConfig varchar (4),
PmAssemblyId varchar (4),
RecursiveBom varchar (4),
RecAllowed varchar (4),
CadId2 varchar (4),
FollowUpMat varchar (4),
LtOffset varchar (4),
DistKey varchar (7),
AlternateItm varchar (4),
UsageProb varchar (6),
PurGrp varchar (6),
DelTimeDays varchar (6),
Vendor bigint,
ValPrice money,
PriceUnitItm varchar (4),
OrderCurr varchar (8),
GLAcct varchar (13),
NbrVarSizeItm varchar (7),
Size1 varchar (7),
Size2 varchar (7),
Size3 varchar (7),
SizeUnit varchar (6),
QtyVarSzItm varchar (7),
FormulaKey varchar (5),
SubItmId varchar (4),
AltId varchar (4),
LongTextLang varchar (4),
BomItmTxt1 varchar (43),
BomItmTxt2 varchar (43),
ObjectTyp varchar (4),
MatGrp varchar (12),
GrProcTime varchar (12),
DocTyp varchar (6),
DocNbr bigint,
DocVersion varchar (5),
DocPart varchar (6),
AvgMatPurity varchar (6),
ClassNbr bigint,
ClassTyp varchar (6),
ResItmCat varchar (4),
SelId varchar (4),
InstanceId varchar (4),
NDisCe varchar (4),
NotDisplay varchar (4),
IdNotDisply varchar (4),
PurchOrg varchar (7),
ReqComp varchar (4),
MultiSelecAllow varchar (4),
AlternDispFmt varchar (4),
OrgArea varchar (13),
AssignNbr bigint,
StorLoc varchar (7),
CoProduct varchar (4),
IntraMat varchar (21),
RestrId varchar (4),
ItmNodeNbr int,
DtLastDtShift varchar (11),
DtShiftedBy varchar (15),
ExplosionTyp varchar (5),
Strategy varchar (4),
RankingOrder int,
AltItmGrp varchar (5),
FollowUpItm varchar (4),
FollowUpGrp varchar (5),
DiscountGrp varchar (5),
ManualChange varchar (4),
ObjDepdentChange varchar (4),
OrigSoBomCat varchar (4),
BillMatOrigSoBomItm varchar (11),
OrginBomItmNbr int,
[Counter] int,
ClassificationNbr int,
SelectionCond varchar (4),
DateShiftHierId int,
SupplyArea varchar (13),
LeadTimeOffOper varchar (13),
UntLeadTimeOffOper varchar (6),
ItmGrp varchar (23),
HistoryCounter int,
CompVariant varchar (8),
AleId varchar (4),
ExtItmId varchar (11),
TempNotUsed varchar (4),
SpecProcBomItm varchar (5),
RefPoint varchar (4),
GlobalIdItmChng varchar (9),
NbrCuInstance int,
FunctionId varchar (4),
CriticalComp varchar (4),
SerialNbrReq varchar (29),
CustMat varchar (7),
MfgNbr varchar (6),


)
