USE SAP 
GO 

Drop Table Vbep

CREATE TABLE Vbep (
Client varchar (5),
SalesDocNbr varchar (12),
SalesDocItmNbr int,
DlvrySchedLineCntr int,
SchedLineCat varchar (4),
ItmRelevantDlvry varchar (3),
SchedLineDt datetime2,
VendConfCreateTime varchar (8),
OrderQty decimal (13, 3),
ConfQty decimal (13, 3),
SalesUnitItm varchar (5),
ReqQty decimal (13, 3),
UnitOfMeasure varchar (5),
ReqDt datetime2,
ReqTyp varchar (4),
PlanningTyp varchar (3),
BusDocNbr bigint,
Items int,
SchedLine int,
Reservation varchar (10),
MaintReq bigint,
PurcReqNbr bigint,
PurcReqDocType varchar (6),
PurcDocCat varchar (3),
GoodsReceipt varchar (3),
InvoiceReceipt varchar (3),
ReturnPack varchar (10),
DtTyp varchar (3),
TransPlanDt varchar (10),
MatAvailDt varchar (10),
LoadingDt varchar (10),
GoodIssDt varchar (10),
CorrQty decimal (13, 3),
DlvryBlock varchar (4),
GrpDefinition int,
ReleaseTyp varchar (3),
FDlvSched bigint,
Size1 decimal (13, 3),
Size2 decimal (13, 3),
Size3 decimal (13, 3),
SizeUnit varchar (5),
FormulaKey varchar (4),
NumSaleSKU int,
DenomSaleSKU int,
AvailConfirm varchar (3),
MvmtTyp varchar (5),
RequisitionItmNbr int,
SchedLineTypEDI varchar (3),
OrderNbr bigint,
PlannedOrder bigint,
BomExplNbr int,
EnginChangeStatus varchar (19),
Guaranteed decimal (8),
MatlStagingTime varchar (8),
Plant varchar (8),
LoadingTime varchar (8),
GoodsIssTime varchar (8),
RouteSched varchar (12),
HandoverDt datetime2,
HandoverTime datetime2,
MatAvDtTpp datetime2,
BlanketPoNbr varchar (24),
BlanketReleaseNbr varchar (12),
BlanketCustLineItm varchar (6),
CustLineSchedNbr varchar (12),
OrginDt datetime2,
)