USE [SAP]
GO

/****** Object:  Table [dbo].[VBRP]    Script Date: 10/20/2017 1:52:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[VBRP];


CREATE TABLE [dbo].[VBRP](
	
Client varchar (5),
BillingDocNbr varchar (12),
BillingDocItm int,
HigherLvlItmBom int,
BilledQty decimal (13, 3),
SalesUnitItm varchar (5),
NumSaleSKU int,
DenomSaleSKU int,
UnitOfMeasure varchar (5),
ScaleQty decimal (13, 3),
BillQtyInSku decimal (13, 3),
ReqQty decimal (13, 3),
NetWeight decimal (15, 3),
GrossWeight decimal (15, 3),
WeightUnit varchar (5),
Volume decimal (15, 3),
VolumeUnitItm varchar (5),
BusArea varchar (6),
PricingDt varchar (10),
ServRenderedDt varchar (10),
ExchangeRate4 decimal (9, 5),
NetVal decimal (13, 5),
PrecedingDocNbr varchar (12),
PrecedingItm int,
RefDocNbr decimal (10),
RefDocItm int,
PrecedSalesDocCateg varchar (3),
SalesDocNbr varchar (12),
SalesDocItm int,
SalesDocRefNbr varchar (3),
Material bigint,
DescSalesOrderItm varchar (50),
PrRefMatl varchar (20),
BatchNbr varchar (16),
MaterialGrp varchar (11),
ItmCat varchar (6),
ItmTyp varchar (3),
ProdHierarchy varchar (20),
ShipPoint varchar (6),
ReplacemtPart varchar (3),
Division varchar (4),
PartnerItmem int,
Plant varchar (6),
DepartCountry varchar (5),
PlantRegion varchar (5),
PlantCounty varchar (5),
CityPlantLoc varchar (6),
TaxClass1Mat varchar (3),
TaxClass2Mat varchar (3),
TaxClass3Mat varchar (3),
TaxClass4Mat varchar (3),
TaxClass5Mat varchar (3),
TaxClass6Mat varchar (3),
TaxClass7Mat varchar (3),
TaxClass8Mat varchar (3),
TaxClass9Mat varchar (3),
StatVal varchar (3),
PricingCarryOut varchar (3),
NbrCashDisc varchar (3),
CashDiscBas money,
MatPricingGrp varchar (4),
AcctAssignGrpMat varchar (4),
CostCenter varchar (12),
VolRebateGrp varchar (4),
CommissionGrp varchar (4),
EanNbr varchar (16),
SalesGrp varchar (5),
SalesOffice varchar (6),
DivisionOrdHeader varchar (4),
[Returns] varchar (3),
EnteredBy varchar (14),
CreatedOn varchar (10),
EntryTime varchar (8),
ValTyp varchar (12),
StorLoc varchar (6),
UpDtGrp varchar (8),
CostDocCurr money,
SubTtl1 money,
SubTtl2 money,
SubTtl3 money,
SubTtl4 money,
SubTtl5 money,
SubTtl6 money,
ExchRateStat decimal (9, 5),
IncompPricing varchar (3),
GeneralIncomp varchar (3),
EanUpc varchar (19),
ProfItmCenter varchar (12),
CustGrp1 varchar (5),
CustGrp2 varchar (5),
CustGrp3 varchar (5),
CustGrp4 varchar (5),
CustGrp5 varchar (5),
DesignWin varchar (5),
SplHandling varchar (5),
SmlOrderStrgy varchar (5),
Cc varchar (5),
EsdFlag varchar (5),
MaterialEntered varchar (20),
RebateBasis1 money,
CoArea varchar (6),
ProfItmegment decimal (10),
WbsElement int,
OrderNbr decimal (12),
TaxJur1 varchar (17),
ItmCreditPrice money,
CredItActive varchar (3),
IntObjNbrConfig varchar (20),
IntObjNbrBatchClass2 decimal (18),
CondUpdate varchar (3),
HghLevlItmmBatch int,
BatchId varchar (3),
UsageId varchar (5),
BomExplNbr int,
SalesDistrictSalesOrder varchar (8),
CustGrpSalesOrder varchar (4),
PriceGrpOrder varchar (4),
DestCtrySalesOrder varchar (5),
ManualPrice varchar (3),
PriceListOrder varchar (4),
RegionOrder varchar (5),
SalesOrderOrg varchar (6),
DistrChannelSaleOrder varchar (4),
AcctSettleStart varchar (10),
MatDetermActive varchar (3),
UsageHighLvlItm varchar (3),
OrderCat varchar (3),
StatisticsDt varchar (10),
BillPlanNbr varchar (11),
BillPlanItm int,
PromotionAKTNR varchar (12),
PromotionKNUMA varchar (12),
SalesDealKNUMA varchar (12),
Preference varchar (3),
TaxAmount money,
OrderReason varchar (5),
BillRule varchar (3),
MainItmPriceRefMat varchar (20),
MatPriceGroupMainItm varchar (4),
CreditPrice2 decimal (25, 16),
PymtGuarantForm varchar (4),
Guaranteed decimal (25, 18),
Reas0Vat varchar (3),
Region varchar (5),
ActivityCdGIT varchar (4),
DistrTypEmployeTax varchar (4),
TaxRelClass varchar (12),
CfopCdExt varchar (12),
IcmsLaw varchar (5),
IpiLaw varchar (5),
SDTaxCd varchar (4),
GrossVal money,
ValContractNbr varchar (12),
ValContracItm int,
PaymCardPlanNbr decimal (10),
TransDt3 varchar (10),
MatGrp1 varchar (20),
MatGrp2 varchar (20),
ConditionGrp1 varchar (4),
ConditionGrp2 varchar (4),
ConditionGrp3 varchar (4),
ConditionGrp4 varchar (4),
ConditionGrp5 varchar (4),
Usage varchar (5),
InflationIdex varchar (7),
IdexBaseDt varchar (10),
UnIitMeasureUse varchar (3),
SalesTaxCd varchar (4),
ContractTyp varchar (3),
ContractNbr varchar (14),
[Text] varchar (52),
AgreedDlvryTime varchar (5),
AcctId varchar (4),
RevRecognItmion varchar (3),
ExchRateLetterCredItm decimal (9, 5),
[Catalog] varchar (16),
RefDoc2 varchar (16),
RefItmNbr2 int,
LogicalSystem varchar (12),
ExternalTransactCat varchar (5),
IssLaw varchar (5),
CofinsLaw varchar (5),
PisLaw varchar (5),
Fund varchar (12),
FundsCenter varchar (18),
FunctionalArea varchar (18),
[Grant] varchar (22),
GenProjPlanGUID varchar (18),
PlanNbrFOper1 decimal (10),
InternalCounter1 int,
PerOfPerfStart varchar (10),
PerOfPerfEnd varchar (10),
PartnerPc varchar (12),
TrdgPartBa varchar (6),
AbbvComplaintReason varchar (6),
ListPrice money,
ListPriceAdj money,
Cost money,
CostPo money,
CostAdj money,
CostActual money,
ResaleProposed money,
Markup money,
Resale money,
FreightEstimated money,
FreightActual money,
ApprovalBaseLine money,
AvnetSubTtl13 money,
AvnetSubTtl14 money,
AvnetSubTtl15 money,
ActualGpCost money,
VistexTtl01 money,
VistexTtl02 money,
VistexTtl03 money,
VistexTtl04 money,
VistexTtl05 money,
VistexTtl06 money,
VistexTtl07 money,
VistexTtl08 money,
VistexTtl09 money,
VistexTtl10 money,
VendorShipDt varchar (10),
EuContractId varchar (12),
EuIsuCd varchar (4),
EuIsuSubCod varchar (4),
EuUserSiteId varchar (12),
EndUserContractVar varchar (12),
EuGenBusCd varchar (22),
ProcessIdNbr decimal (10),
RefundCd varchar (5),
ReturnReason varchar (5),
CondRecOrderNbr varchar (16),
ConditionVal money,
DisputeCase varchar (18),
FundUsgItm varchar (18),
ClaimsTax varchar (3),
TransDt1 varchar (10),
DpChainNbr varchar (16),
TransactionNbr int,
DocSeqNbr int,
BudgetPeriod varchar (12),
WorkPeriod int,
PlanNbrOperation2 decimal (10),
InternalCounter2 int,
ConfigurationId varchar (22),
RevenueAcctTyp varchar (12),
PrecCatExt varchar (6),
ReqmntSegment varchar (18),
StkSegment varchar (18),
UsGovt varchar (24),
DocCurrCost money,
LocalCurrency money,
ExchRateAcctFIPost decimal (9, 5),
CfAllowed decimal (5, 2),
PriceReval decimal (5, 2),
RatioFrom decimal (9),
RatioTo decimal (9),
ActualRate decimal (9, 5),
CfApplicInd2 varchar (3),
CfApplicInd1 varchar (3),
CostTyp varchar (5),
SalesMarginInv money,
CustMatProjNbr varchar (41),
CustMatDesignRegNbr varchar (51),
CondVal1 money,
ConditionVal1 money,
ConditionVal5 money,
ConditionVal4 money,
CaoActiv varchar (3),
SerialNbr varchar (21),
ConditionVal2 money,
ConditionVal3 money,
DPAStepNbr int,
SalesDeal varchar (12),
DrActiveStat varchar (3),
MatchTyp varchar (6),

) ON [PRIMARY]

GO



