USE SAP 
GO 


DROP TABLE Rbkp





CREATE TABLE Rbkp(
Client varchar (6),
AcctDocNbr bigint,
FY int,
DocTyp varchar (5),
DocDt datetime2,
DocPostingDt datetime2,
UserName varchar (15),
TransCd varchar (23),
EnteredOnDt datetime2,
EnteredAtTime time,
TransactEventTyp varchar (5),
RefDocNbr varchar (19),
CoCd varchar (7),
Vendor varchar (13),
OrderCurr varchar (6),
ExchangeRate decimal (9, 5),
GrossInvAmt money,
UnplandDlvryCosts money,
TaxAmountWithSign money,
TaxCd1 varchar (5),
NotInUse money,
NbrtInUse varchar (5),
PayTerms varchar (7),
DiscountDays1 decimal (3),
DiscountPct1 decimal (5, 3),
DiscountDays2 decimal (3),
DiscountPct2 decimal (5, 3),
PmtPeriod decimal (3),
DiscountAmt money,
PostInvoiceId varchar (4),
DocHeaderTxt varchar (28),
SapRelease varchar (7),
LogSys varchar (13),
CalcTax varchar (4),
ReversedWith varchar (13),
FiscYrReverseDoc int,
TaxCd2 varchar (5),
TaxJur2 varchar (18),
IvCat varchar (4),
SevTaxCdsId varchar (4),
InvVerTyp varchar (4),
InvStat varchar (4),
DocCond varchar (13),
VendorCond varchar (13),
InvReduction money,
TaxInvReduction money,
ManAccpdNetAmt money,
TaxAccptdManual money,
VendErrorNet money,
TaxVendError money,
AutoAcceptedId varchar (4),
IsrSubscribeNbr varchar (14),
IsrCheckDigit varchar (5),
IsrRefNbr varchar (30),
WTaxBase money,
WTaxExempt money,
WTaxCd varchar (5),
SvcId varchar (4),
SupplCntry varchar (6),
ScbId varchar (6),
RateForTaxes decimal (9, 5),
Payer varchar (13),
PartBankTyp varchar (7),
HouseBank varchar (8),
AssignNbr varchar (21),
PmtBlock varchar (4),
PmtMethod varchar (4),
BaselineDt datetime2,
PmtRef varchar (33),
InvoiceRef varchar (13),
FYInvoice int,
InvestId varchar (4),
ReportingCntry varchar (6),
EuTriangDealId varchar (4),
TaxReportDt datetime2,
NotaFiscalTyp varchar (5),
BranchNbr varchar (7),
EntryProfile varchar (15),
SectionCd varchar (7),
Name1 varchar (38),
Name2 varchar (38),
Name3 varchar (38),
Name4 varchar (38),
PostalCd varchar (13),
City varchar (38),
DestCountry varchar (6),
StreetAddress varchar (38),
PoBox varchar (13),
PoBoxPostalCd varchar (13),
PostBankNbr varchar (19),
BankAcctNbr varchar (21),
BankNbr varchar (18),
BankCountryKey varchar (6),
TaxNbr1 varchar (19),
TaxNbr2 varchar (14),
VatLiability varchar (4),
EqualizationTaxId varchar (4),
Region varchar (6),
BankControlKey varchar (5),
InstructionKey varchar (5),
DMEId varchar (4),
[Language] varchar (4),
OneTimeAcctId varchar (4),
PayeeCd varchar (19),
TaxTyp varchar (5),
TaxNbrTyp varchar (5),
NaturalPerson varchar (4),
TaxNbr3 varchar (21),
TaxNbr4 varchar (21),
RefBankDetail varchar (23),
RepsName varchar (13),
TypBus varchar (33),
TypIdustry varchar (33),
Title varchar (18),
VatRegNbr varchar (23),
EnteredByExtSysUser varchar (15),
InvRecptDt datetime2,
PmtMethSupl varchar (5),
PlanLvl varchar (5),
PlanDt datetime2,
FixedPmtTerms varchar (4),
RelId varchar (4),
EnteredBy varchar (15),
BusPlace varchar (7),
AcctNbrBranch varchar (13),
BusArea varchar (7),
LotNbr varchar (13),
Txt varchar (53),
PrePmtStatus varchar (4),
InvoiceNbr varchar (23),
AssignTestInvoice varchar (4),
NextAssignTest datetime2,
EndAssignTestPeriod datetime2,
OriginInvoiceDocNbr varchar (13),
FYOriginInvoice int,
CopiedInvoiceDocNbr varchar (13),
FyInvCopy int,
CreatorOfCopy varchar (15),
GLAcct varchar (13),
TransLogInvoiceVerify varchar (4),
MdExchangeRate decimal (28, 14),
TranslationDt datetime2,
RefKeyLineItm varchar (23),
Billback varchar (5)

)
