--ALTER TABLE SAP.dbo.Ekpo SET (SYSTEM_VERSIONING = OFF)
-- --(HISTORY_TABLE= dbo.SAP.dbo.EkpoHistory));

--DROP TABLE SAP.dbo.Ekpo
--DROP TABLE SAP.dbo.EkpoHistory


CREATE TABLE SAP.dbo.Ekpo
	(
	Client varchar (5),
	PoNbr bigint,
	PoItmNbr INT,
	PoDelId varchar (3),
	RfqStatus varchar (3),
	ChangedOn datetime2,
	ShortText varchar (48),
	Material bigint,
	MaterialEMATN bigint,
	CompanyCd varchar (6),
	Plant INT,
	StorLoc varchar (6),
	ReqTrackingNbr varchar (12),
	MatGrp varchar (11),
	NbrPurchInfoRecord varchar (12),
	VendorMatNbr varchar (42),
	TargetQty decimal (14, 3),
	PoQty decimal (14, 3),
	PoUnit varchar (4),
	OrderPriceUnit varchar (4),
	NumQtyConversion decimal (2),
	DenomQtyConversion decimal (2),
	NumEqualTo decimal (2),
	DenomEqualTo decimal (2),
	PoNetPrice money,
	PriceUnit decimal (6),
	PoNetVal money,
	PoGrossOrder money,
	QuoteDeadline datetime2,
	GrProcessingTime decimal (4),
	TaxSalesPurchCd varchar (4),
	SettlementGrp1 varchar (2),
	StkTyp varchar (3),
	InfoUpdate varchar (3),
	PrintPrice varchar (3),
	EstPrice varchar (3),
	NbrRemindExp decimal (2),
	[1stRemindExped] decimal (2),
	[2ndRemindExped] decimal (2),
	[3rdRemindExped] decimal (2),
	OverDlvryTol decimal (3, 1),
	[Unlimited] varchar (3),
	UnderDlvryTol decimal (4, 1),
	ValTyp varchar (12),
	ValCat varchar (3),
	RejectionId varchar (3),
	QuoteComment varchar (2),
	DlvryCompletedId varchar (3),
	FinalInvoiceId varchar (3),
	PoItmCat varchar (3),
	AcctAssignmentCat varchar (3),
	ConsumptionPosting varchar (3),
	[Distribution] varchar (2),
	PartialInvoiceId varchar (2),
	GrId varchar (3),
	GrNonvaluated varchar (3),
	InvoiceReceipt varchar (3),
	GRBasedIV varchar (3),
	AcknowlReqd varchar (3),
	OrderAcknowl varchar (25),
	Agreement varchar (12),
	Agreementitm varchar (7),
	ReconciliationDt datetime2,
	AgreedCumQty decimal (5, 3),
	FirmZon decimal (2),
	TradeOffZone decimal (2),
	BindingOnMRP varchar (2),
	Exclusion varchar (2),
	BaseUnitMeasure varchar (4),
	ShippingInstructions varchar (4),
	TargetVal money,
	NonDeductible money,
	ReleaseOrderQty decimal (11, 3),
	PriceDt datetime2,
	PoCat varchar (3),
	EffectiveValItm money,
	Commitments varchar (2),
	Customer varchar (12),
	ManualAddres varchar (12),
	VendorConditionGrp varchar (2),
	NoCashDiscount varchar (2),
	UpdtGrp varchar (5),
	PlanDlvryTime decimal (4),
	NetWeight decimal (10, 3),
	UnitWeight varchar (4),
	TaxJurisdiction varchar (12),
	PrintRelevant varchar (2),
	SpecialStk varchar (3),
	SettlementNbr varchar (12),
	SettlementItmNbr varchar (6),
	NotChangeable varchar (2),
	QMControlKey varchar (2),
	CertificateTyp varchar (2),
	EanUpcNbr varchar (19),
	ConfirmControlKey varchar (6),
	RevisionLevel varchar (2),
	Fund varchar (2),
	FundsCenter varchar (2),
	CommitmentItm varchar (2),
	BusinessAreaPartner varchar (2),
	PartnerAssumnedBA varchar (2),
	ProfitCenter varchar (12),
	PartnerProfitCenter varchar (2),
	PriceDtCat varchar (3),
	GrossWeight decimal (5, 3),
	Volume decimal (5, 3),
	VolumeUnit varchar (2),
	Incoterms1 varchar (5),
	Incoterms2 varchar (30),
	AdvanceProcurement varchar (2),
	PriorVendor varchar (2),
	VendorSubrange varchar (4),
	PackageNbr varchar (12),
	InvoicingPlanNbr varchar (2),
	CurrentlyNotUsed money,
	Statistical varchar (3),
	HighLvlItm varchar (7),
	LatestGrDt datetime2,
	Vendor varchar (12),
	SubcontractingVendor varchar (3),
	CrossplantConfigMat varchar (2),
	MatCat varchar (2),
	KanbanId varchar (2),
	DlvryAddressNbr varchar (12),
	InternalObjectNbr varchar (20),
	ERS varchar (3),
	GrBSettFrom datetime2,
	LastTransmission datetime2,
	TimeOfTransmission varchar (8),
	SequentialNbr varchar (6),
	Promotion varchar (2),
	AllocationTableNbr varchar (2),
	AllocationTableItmNbr varchar (7),
	Points decimal (5, 3),
	PointsUnit varchar (2),
	SeasonCat varchar (2),
	SeasonYear varchar (2),
	SettleGrp2 varchar (2),
	SettleGrp3 varchar (2),
	Settlement varchar (3),
	MatLedgerActive varchar (2),
	MinRemShelfLife decimal (3),
	RfqNbr varchar (12),
	RfqItmNbr varchar (7),
	OriginConfig varchar (2),
	QuotaArrangeUsage varchar (2),
	SpecialStkStkTransId varchar (3),
	PurchRequisitionNbr varchar (12),
	PurchRequisitionItmNbr varchar (7),
	MatTyp varchar (6),
	SubItmCat varchar (2),
	SubItmsExist varchar (2),
	Subtotal1 money,
	Subtotal2 money,
	Subtotal3 money,
	Subtotal4 money,
	Subtotal5 money,
	Subtotal6 money,
	ProcessingKey varchar (2),
	MaxCMGQty decimal (5, 3),
	MaxCPGQ decimal (5, 3),
	ReturnsItm varchar (3),
	AllocationTableRel varchar (3),
	ReasonForOrder varchar (5),
	DlvryTypReturns varchar (6),
	MatFreightGrp varchar (2),
	DiscountInKind varchar (2),
	NcmCd varchar (2),
	MatUsage varchar (2),
	MatOrigin varchar (2),
	ProducedInHouse varchar (2),
	MatCfopCat varchar (2),
	CreationProfile varchar (2),
	NextFcstSched datetime2,
	NextJitSched datetime2,
	ValuationSpecialStk varchar (3),
	RebateBasis money,
	JITId varchar (2),
	InflationIndex varchar (2),
	InflationIndexDt datetime2,
	MfgPartProfile varchar (2),
	FinalDlvry varchar (3),
	PartialDlvryAtItmLevelStkTransfer varchar (3),
	UnitsMeasureUsage varchar (2),
	RoundingProfile varchar (2),
	StandardVariant varchar (2),
	ConfigurationChanged varchar (2),
	NoInvoiceForThis varchar (2),
	MfgPartNbr varchar (42),
	Mfg varchar (12),
	ExternalMfg varchar (2),
	ShippingBlock varchar (2),
	Requisitioner varchar (14),
	RecTimeZone varchar (7),
	PeriodId varchar (2),
	SvcBasedInvoiceVerification varchar (2),
	MrpArea varchar (2),
	ConditionsForItmNoInvoice varchar (2),
	ExtPlanning varchar (2),
	StkTransCat varchar (3),
	GrantNbr varchar (2),
	FunctionalArea varchar (2),
	PoItmStat varchar (2),
	IssuingStorLoc varchar (6),
	EarmarkedFunds varchar (2),
	EarmarkedFundsDocItm varchar (5),
	AcceptanceAtOrigin varchar (2),
	SvcBasedCommit varchar (2),
	ReqUrgency varchar (4),
	ReqPriority varchar (5),
	ReceivingPoint varchar (2),
	RejectionReason varchar (4),
	CrmSalesOrderNbr varchar (2),
	CrmSalesOrderItmNbr varchar (8),
	CrmRefOrderNbr varchar (2),
	CrmRefSalesOrderItmNbr varchar (2),
	LastChangerSysTyp varchar (2),
	SourceStkTyp varchar (3),
	CqControlTyp varchar (2),
	NoCQTransmission varchar (2),
	GrReasonCd varchar (2),
	CumulativeGRs decimal (5, 3),
	EwmDlvryToleranceCheck varchar (2),
	ItmNbrLength varchar (2),
	ExternalSorting varchar (7),
	ExternalHierarchyCat varchar (2),
	ItmGenerated varchar (2),
	DependentFree varchar (2),
	StructureCat varchar (2),
	AdviceCd varchar (2),
	AcceptancePeriod varchar (4),
	IuidRelevant varchar (2),
	[Configuration] varchar (22),
	ConfigurationLine varchar (14),
	AuthorizationNbr varchar (4),
	ProgramId1 varchar (27),
	SupplierSalesOrderNbr varchar (17),
	ReqDt datetime2,
	CarrierAcctNbr varchar (23),
	CarrierPmtMethod varchar (4),
	ReasonCd varchar (5),
	HardwarePartNbr varchar (24),
	HardwareSerialNbr varchar (42),
	CarrierACNbr varchar (2),
	RefSiteForPurch varchar (2),
	ReferenceItm varchar (7),
	OriginProfile varchar (7),
	KeyInSourceSys varchar (2),
	PutBackId varchar (2),
	OrderListItmNbr varchar (7),
	Consignment varchar (2),
	SoLineItmNbr varchar (8),
	EstShipDt datetime2,
	EstDockDt datetime2,
	ExcB2BPoLineUpDt varchar (10),
	DifferentialInvoicing varchar (8),
	RiskRelevancy varchar (10),
	BillingRelCrm varchar (10),
	NbrSerialNbrs varchar (3),
	RetentionInPercent decimal (4, 2),
	DownPmtId varchar (6),
	DownPmtPct decimal (4, 2),
	DownPmtAmt money,
	DueDtForDownPmt datetime2,
	StoreReturn varchar (10),
	ExternalDocNbr Bigint,
	ExternalDocItmNbr bigint,
	LogSys varchar (10),
	CentralContractNbr varchar (2),
	CentralContractItmNbr varchar (12),
	BlockingReasonId varchar (12),
	BlockingReasonText varchar (2),
	RTConsumption varchar (2),
	FixedDt varchar (12),
	FmBudgetPeriod varchar (2),
	MaxRetailPriceRelevant varchar (2),
	TypSubcontracting varchar (2),
	SerialNbrProfile varchar (6),
	SpecialStkSubcontracting varchar (3),
	WBSElement varchar (10),
	CustNbr varchar (10),
	SalesDistDocNbr bigint,
	SalesDistDocItmNbr bigint,
	OwnerStk varchar (10),
	ShippingTyp varchar (2),
	HandoverLoc varchar (2),
	GIBasedGR varchar (8),
	TaxCdAutoDetermined varchar (2),
	ManualTaxCdReason varchar (2),
	TaxIncentiveTyp varchar (2),
	TaxSubjectToSt varchar (2),
	IncentiveId varchar (2),
	USGovt varchar (2),
	StkSegment varchar (2),
	ReqSegment varchar (2),
	FlagSpecialBuy varchar (3),
	CustName varchar (37),
	DtCd varchar (32),
	LotCd varchar (17),
	GovtContractNbr varchar (42),
	PriorityRating varchar (13),
	FunLoc varchar (17),
	DtTimeStamp datetime2,
	SalesDocNbr bigint,
	SalesDocItmNbr bigint,
	Shc varchar (8),
	SpecialFlagId varchar (16),
	FreightConsolidation varchar (16)
	,SqlStartTime datetime2 GENERATED ALWAYS AS ROW START NOT NULL
    ,SqlEndTime datetime2 GENERATED ALWAYS AS ROW END NOT NULL
	,PERIOD FOR SYSTEM_TIME (SqlStartTime, SqlEndTime),
	CONSTRAINT PkEkpo PRIMARY KEY(PoNbr, PoItmNbr)
)

WITH
	(
		SYSTEM_VERSIONING = ON (HISTORY_TABLE= dbo.EkpoHistory)
	)
;