USE SAP
GO

DROP TABLE Mvke;

CREATE TABLE MVKE(
Client varchar (4),
Material bigint,
SalesOrg varchar (5),
DistrChannel int,
ValuationTyp varchar (2),
MatlStatsGrp varchar (2),
VolRebateGrp varchar (3),
CommissionGrp varchar (3),
NbrCashDisc varchar (2),
DChainSpec varchar (3),
ValidFrom datetime2,
MinOrderQty decimal (13, 3),
MinDlvryQty decimal (13, 3),
MinMakeOrderQty decimal (13, 3),
DlvryUnit decimal (13, 3),
UnitOfMeasure varchar (4),
SalesUnitItm varchar (4),
ItmCatGrp varchar (5),
Plant varchar (5),
ProdHierarchy varchar (19),
PrRefMatl varchar (19),
MatPricingGrp varchar (3),
AcctAssignGrpMat varchar (3),
DesignWin varchar (4),
SplHandling varchar (4),
SmlOrderStrgy varchar (4),
Cc varchar (4),
EsdFlag varchar (4),
AssortGrade varchar (3),
ExtAsstPrio varchar (2),
LpForStkRes varchar (3),
LpDistrCtrs varchar (3),
ListingActive varchar (2),
ListedFromStore datetime2,
ListedToStore datetime2,
ListedFromDistCntr datetime2,
ListedToDistCntr datetime2,
ForSaleFromDtStore datetime2,
ForSaleTillStore datetime2,
ForSaleFromDtDistCntr datetime2,
ForSaleTillDistCntr datetime2,
NcnrFlag varchar (2),
LiquiDtFlag varchar (2),
CustomProduct varchar (2),
SwLicenseReq varchar (2),
NdaRequired varchar (2),
DownloadFlag varchar (2),
DualMarkId varchar (2),
WaiverReq varchar (2),
GlbInv varchar (2),
NaftaFlag varchar (2),
RoundingProfile varchar (5),
UomGrp varchar (5),
MaxDlvryQty decimal (13, 3),
RackjobberFlag varchar (2),
PriceFixing varchar (2),
VarSaleNotAllow varchar (2),
CompetitionCharacter varchar (2),
PpSorting int,
EmpGrp varchar (5),
PrintColumn int,
BaseUnitMeasureStatTtl varchar (4),
NbrNoTtl varchar (2),
AssignTtlFieldCat1 varchar (2),
AssignTtlFieldCat2 varchar (2),
AssignTtlFieldCat3 varchar (2),
AssignTtlFieldCat4 varchar (2),
PriceBandCat varchar (3),
StartDesignWIdat datetime2,
EndDesignWIdt datetime2,
GrandfatherDt datetime2,
StkingProfile varchar (11),
FamilyPartNbr varchar (19),
UpgradeCat varchar (41),
EndOfSupportLifeDt datetime2,
ContribPoints varchar (11),
LastTimeBuyDt datetime2,
UncostedItm varchar (11),
ProductAuth varchar (61),
ProductAuth2 varchar (61)


)