Drop Table sap.dbo.Konp


Create Table sap.dbo.Konp
(
Client varchar (4),
NbrCondRecBatch varchar (11),
SequNbrOfCond int,
[Application] varchar (3),
CondTyp varchar (5),
TextNbr varchar (11),
ScaleTyp varchar (2),
ScaleBasis varchar (2),
ScaleQty decimal (15, 3),
ScaleUom varchar (3),
ScaleVal decimal (15, 2),
ScaleCurr varchar (5),
CalcTyp varchar (2),
RateNoScaleExists decimal (11, 2),
CondCurr varchar (5),
PricingUnit decimal (7),
CondUnitOfMeasure varchar (5),
ScaleGrp varchar (5),
NumForConv decimal (7),
DenomForConv decimal (7),
UnitOfMeasure varchar (5),
LowerLimItm decimal (11, 2),
UpperLimitCondRate decimal (11, 2),
PlannedCondVal decimal (15, 2),
CumulativeGuaranteeDiscount decimal (15, 2),
CumulativeAccr decimal (15, 2),
CumCondCurr varchar (5),
PlannedBasis decimal (15, 2),
Exclusion varchar (2),
SoldToPartyId varchar (11),
Vendor varchar (11),
TaxCd varchar (3),
DeleteId varchar (2),
CondItmIndex int,
MatRebateSettle varchar (19),
Accruals decimal (11, 2),
Retroactive varchar (2),
CondRecStatus varchar (2),
Promotion varchar (11),
SalesDeal varchar (11),
SalesQuote varchar (11),
AddValDays int,
FixedValDt datetime2,
PayTerms varchar (5),
MaxNbrSalesOrder int,
MinCondBaseVal decimal (15, 3),
MaxCondBaseVal decimal (15, 3),
MaxCondVal decimal (13, 2),
IncrementScale int,
PricingScale int,
RelToPricing varchar (2),
SalValIncVat varchar (11),
Agreement varchar (11),
WTaxCd varchar (3),
ContractTyp varchar (2),
ContractNbr varchar (14),
FlowTyp varchar (5),
MatrixMaint varchar (2),
ReleaseStat varchar (2),
StatusBvCA varchar (2),
ContractTyp2 varchar (2),
ContractNbr2 varchar (14),
FlowTyp2 varchar (5),
)