USE [SAP]
GO

/****** Object:  Table [dbo].[Mseg]    Script Date: 10/23/2017 7:29:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

drop table mseg

CREATE TABLE [dbo].[Mseg](
	[Client] [varchar](5) NULL,
	[MaterialDocNbr] [bigint] NULL,
	[MatDocYearMJAHR] [int] NULL,
	[MatDocItmZEILE] [int] NULL,
	[DocLineId] [int] NULL,
	[ParentId] [int] NULL,
	[Level] [int] NULL,
	[MovementTyp] [int] NULL,
	[AutoCreated] [varchar](3) NULL,
	[Material] [bigint] NULL,
	[Plant] [int] NULL,
	[StorLoc] [varchar](6) NULL,
	[BatchNbr] [varchar](12) NULL,
	[PostInspectStk] [varchar](3) NULL,
	[BatchStatusKey] [varchar](3) NULL,
	[BatchRestr] [varchar](3) NULL,
	[SpecialStk] [varchar](3) NULL,
	[Vendor] [varchar](12) NULL,
	[SoldToPartyId] [varchar](12) NULL,
	[SalesOrderNbr] [bigint] NULL,
	[SalesOrderItm] [int] NULL,
	[SalesOrderDlvrySched] [int] NULL,
	[Dist] [varchar](12) NULL,
	[Returns] [varchar](3) NULL,
	[OrderCurrency] [varchar](7) NULL,
	[AmtLocalCurr] [money] NULL,
	[DlvryCostsLocalCurr] [money] NULL,
	[AmountAltPriceCtrl] [money] NULL,
	[DCIdReval] [varchar](3) NULL,
	[RevaluationAmtBackPost] [money] NULL,
	[ValTyp] [varchar](12) NULL,
	[SchedQty] [decimal](13, 3) NULL,
	[UnitOfMeasure] [varchar](5) NULL,
	[UnitOfEntryQty] [decimal](13, 3) NULL,
	[UnitOfEntry] [varchar](5) NULL,
	[QtyPoPriceUnit] [decimal](13, 3) NULL,
	[OrderPriceUnit] [varchar](5) NULL,
	[PoNbr] [varchar](12) NULL,
	[PoItmNbr] [int] NULL,
	[FYRefDoc] [int] NULL,
	[RefDoc] [bigint] NULL,
	[RefDocItm] [int] NULL,
	[MatDocYear] [int] NULL,
	[MatDoc] [varchar](12) NULL,
	[MatDocItmSMBLP] [int] NULL,
	[DlvryCompleteId] [varchar](3) NULL,
	[EquipmentNbr] [varchar](20) NULL,
	[Recipient] [varchar](14) NULL,
	[UnloadingPoint] [varchar](27) NULL,
	[BusArea] [varchar](6) NULL,
	[CoArea] [int] NULL,
	[TradingPartBusArea] [varchar](6) NULL,
	[ClearingCoCd] [varchar](6) NULL,
	[CostCenter] [varchar](12) NULL,
	[NbrNotUse] [varchar](18) NULL,
	[OrderNbr] [bigint] NULL,
	[Asset] [bigint] NULL,
	[AssetSubNbr] [int] NULL,
	[CctPostingStatId] [varchar](3) NULL,
	[OrderPostStatId] [varchar](3) NULL,
	[ProjPostStatId] [varchar](3) NULL,
	[PaPostStatId] [varchar](3) NULL,
	[FY] [int] NULL,
	[PostPrevPer] [varchar](3) NULL,
	[PostTtlPrYearId] [varchar](3) NULL,
	[CoCd] [varchar](6) NULL,
	[AcctDocNbr1] [varchar](12) NULL,
	[AcctDocLineItmNbr] [int] NULL,
	[AcctDocNbr2] [varchar](12) NULL,
	[LineItm] [int] NULL,
	[Reservation] [bigint] NULL,
	[ReservationItmBbr] [int] NULL,
	[FinalIssue] [varchar](3) NULL,
	[Qty2] [decimal](13, 3) NULL,
	[StatRelevant] [varchar](3) NULL,
	[ReceivingMat1] [varchar](20) NULL,
	[ReceivingIssuingPlant] [varchar](6) NULL,
	[ReceivingStorLoc] [varchar](6) NULL,
	[ReceivingIssuingBatch] [varchar](12) NULL,
	[TransBatchStat] [varchar](3) NULL,
	[TransBatchStatKey] [varchar](3) NULL,
	[ValTypTransBatch] [varchar](12) NULL,
	[SpIdStckTransBatch] [varchar](3) NULL,
	[MvmtId] [varchar](3) NULL,
	[Consumption] [varchar](3) NULL,
	[ReceiptId] [varchar](3) NULL,
	[NonValueGoodsReceipt] [varchar](3) NULL,
	[NbrOfPallets] [decimal](11, 0) NULL,
	[WarehouseNbr] [varchar](5) NULL,
	[StorTyp] [varchar](5) NULL,
	[StorBin] [varchar](12) NULL,
	[StkCat] [varchar](3) NULL,
	[MvmtTyp] [int] NULL,
	[TransReqNbr] [bigint] NULL,
	[TransReqItm] [int] NULL,
	[WarehousePostId] [varchar](3) NULL,
	[IntStPstSrcId] [varchar](3) NULL,
	[InterPostDest] [varchar](3) NULL,
	[DynamicBin] [varchar](3) NULL,
	[PostingChangeNbr] [bigint] NULL,
	[TransPrior] [varchar](3) NULL,
	[TransOrderNbr] [bigint] NULL,
	[NbrGrSlips] [int] NULL,
	[ReasonForMvmt] [int] NULL,
	[ShippingInstruct] [varchar](4) NULL,
	[ShipInstructCompliance] [varchar](4) NULL,
	[RealEstateKey] [varchar](10) NULL,
	[CostObject] [varchar](14) NULL,
	[ProfitSegment] [bigint] NULL,
	[ProfitCenter] [bigint] NULL,
	[WbsElement] [int] NULL,
	[Network] [varchar](14) NULL,
	[PlanNbrOper] [bigint] NULL,
	[InternalCounter] [bigint] NULL,
	[OrderItmNbr] [int] NULL,
	[PartnerAccNbr] [varchar](12) NULL,
	[CommitmentItm] [varchar](16) NULL,
	[GLAcct] [bigint] NULL,
	[QtyOrderUnit] [decimal](13, 3) NULL,
	[PoUnitMeasure] [varchar](5) NULL,
	[RevGrDespInv] [varchar](3) NULL,
	[VendorSupplied] [varchar](12) NULL,
	[ExtPostAmtLocalCurr] [money] NULL,
	[SalValIncVat] [money] NULL,
	[Promotion] [varchar](12) NULL,
	[SeqNbrAccAss] [int] NULL,
	[ShelfLifeExp] [varchar](16) NULL,
	[IntObjNbrBatchClass2] [varchar](20) NULL,
	[ExtEnteredSalesVal] [money] NULL,
	[PartnerPc] [bigint] NULL,
	[RecOrderTyp] [varchar](3) NULL,
	[Fund] [varchar](12) NULL,
	[FundsCenter] [varchar](18) NULL,
	[StkMat] [varchar](20) NULL,
	[ReceivingMat2] [varchar](20) NULL,
	[QtyString] [varchar](6) NULL,
	[ValString] [varchar](6) NULL,
	[QtyUpdating] [varchar](3) NULL,
	[ValUpDt] [varchar](3) NULL,
	[TtlValStk] [decimal](13, 3) NULL,
	[ValTtlValStk] [money] NULL,
	[PriceControl] [varchar](3) NULL,
	[FunctionalArea] [varchar](18) NULL,
	[ReferenceDtSettle1] datetime2 NULL,
	[SalValWOVat] [money] NULL,
	[ReferenceDtSettle2] datetime2 NULL,
	[AutoPo] [varchar](3) NULL,
	[DlvryNbrNoteQty] [decimal](13, 3) NULL,
	[DlvryNbrNoteUnit] [varchar](5) NULL,
	[Valuation] [varchar](3) NULL,
	[StatusGRDoc] [varchar](3) NULL,
	[OrigLineMatDoc] [int] NULL,
	[AltBaseAmnt] [money] NULL,
	[TaxCd1] [varchar](4) NULL,
	[TaxJur1] [varchar](17) NULL,
	[MatNbrMfgPartNbr] [varchar](20) NULL,
	[GoodsIssueReEvalPerformed] [varchar](3) NULL,
	[TaxCd2] [varchar](4) NULL,
	[DtMfg] datetime2 NULL,
	[StagingId] [varchar](3) NULL,
	[SalesOrderNbrStk] [bigint] NULL,
	[SalesOrderItmStk] [int] NULL,
	[SoWbsElement] [int] NULL,
	[CalcOfValOpen] [varchar](3) NULL,
	[AcctId] [varchar](4) NULL,
	[BusProcess] [varchar](14) NULL,
	[SupplVendor] [varchar](12) NULL,
	[ActivityTyp] [varchar](8) NULL,
	[VendorStkValId] [varchar](3) NULL,
	[Grant] [varchar](22) NULL,
	[StkTypMod] [varchar](3) NULL,
	[GtsStkTyp] [varchar](3) NULL,
	[ExciseDutyStatus] [varchar](3) NULL,
	[UserName2] [varchar](14) NULL,
	[ChangedOn] datetime2 NULL,
	[SysTime] [varchar](11) NULL,
	[NonDeductible] [money] NULL,
	[Condkey1] [varchar](4) NULL,
	[Condkey2] [varchar](4) NULL,
	[Text] [int] NULL,
	[EarmarkedFundsDocNbr] [varchar](12) NULL,
	[EarmarkedFundsDocItm] [int] NULL,
	[MultiAcctAssgt] [varchar](3) NULL,
	[TransactEventTyp2] [varchar](4) NULL,
	[DocPostingDt2] datetime2 NULL,
	[EnteredOnDt2] datetime2 NULL,
	[EnteredAtTime2] [varchar](11) NULL,
	[UserName] [varchar](14) NULL,
	[RefDocNbr] [varchar](51) NULL,
	[TransactionCode3] [varchar](22) NULL,
	[Delivery1] [varchar](12) NULL,
	[DlvryItm2] [int] NULL,
	[OwnerOfStk] [varchar](12) NULL,
	[StkSegment] [varchar](18) NULL,
	[RecStkSeg] [varchar](18) NULL
) ON [PRIMARY]

GO


