USE [SAP]
GO
 
DROP TABLE Eban

CREATE TABLE [dbo].[Eban](
Client varchar (5),
PurchReqNbr bigint,
RequisitionItmNbr int,
PurchReqDocTyp varchar (6),
PurchDocCatBSTYP varchar (3),
ControlId varchar (3),
PurOrgData varchar (3),
Status varchar (3),
CreationId varchar (3),
RelId varchar (3),
RelStatus varchar (10),
RelStgyPurchReq varchar (4),
PurchGrp varchar (5),
CreatedBy varchar (14),
CreatedOn datetime2,
Requisitioner varchar (14),
PurchInfoRec varchar (51),
Material bigint,
MatNbrMfgPartNbr varchar (26),
Plant int,
StorLoc varchar (6),
ReqTrackNbr varchar (12),
MatGrp varchar (11),
SupplyPlant int,
SchedQty int,
UnitOfMeasure varchar (6),
ShortageQty int,
RequisitionDt datetime2,
DlvryDtCat varchar (11),
DlvryDt datetime2,
PurchReqReleaseDt datetime2,
GrProcTime int,
ValPrice money,
PriceUnitItm int,
ItmCat varchar (6),
AcctAssignCat varchar (3),
Consumption varchar (3),
AcctChangeable varchar (3),
DistId varchar (3),
PartialInvoiceId varchar (3),
GoodsReceipt varchar (3),
NonValueGoodsReceipt varchar (3),
InvoiceReceipt varchar (3),
Vendor varchar (12),
FixedVendor varchar (12),
PurchOrg varchar (11),
PurchDocCatVRTYP varchar (6),
Agreement varchar (12),
AgreeItm int,
InfoRecOrderNbr bigint,
AssignedSrceSupply varchar (3),
QuotaArrange varchar (12),
QuotaArngeItm int,
MrpCntrlrMatPlan varchar (5),
BomExplNbr varchar (10),
LastResubmissDt datetime2,
ResubmissionInterval int,
NbrResubmission int,
PurchDocNbr bigint,
PurchDocItmNbr bigint,
OrderDtSchedLine datetime2,
PoQty int,
EntrySheet varchar (12),
ValTyp varchar (12),
Commitments varchar (3),
PurchReqClosed varchar (3),
Reservation bigint,
SpecialStk varchar (11),
SettleReserNbr bigint,
SettleItmNbrReservation int,
FixedId varchar (6),
PoUnitMeas varchar (5),
RevisionLevel varchar (4),
AdvanceProcure varchar (3),
PackageNbr bigint,
KanbanId varchar (11),
RequisitionPricePo varchar (3),
IntObjNbrConfig bigint,
RelGrp varchar (21),
RelNotEffected varchar (3),
Promotion varchar (12),
BatchNbr varchar (12),
SpIdStckTfr varchar (3),
ProdVersion varchar (6),
CommitmentItm varchar (16),
FundsCenter varchar (18),
Fund varchar (12),
OriginOfConfig varchar (3),
CrossPlanConfigMat varchar (20),
CommittedQty int,
CommitedDt datetime2,
MatCat varchar (11),
Address varchar (12),
NbrDlvryAddress int,
SoldToPartyId bigint,
VendorSupplied varchar (12),
ScVendor varchar (3),
Valuation varchar (3),
OrderCurr varchar (7),
VendMatNbr varchar (50),
OverallReqRel varchar (3),
MfgPartProfile varchar (6),
UnitMeasureUse varchar (3),
Language varchar (3),
StandardVariant varchar (14),
MfgPartNbr varchar (42),
Mfg varchar (26),
ExternalMfgCd varchar (12),
FrameworkOrder varchar (12),
FrameworkOrderItm int,
PlDlvryTime int,
MrpArea varchar (12),
DtTime datetime2,
FunctionalArea varchar (18),
[Grant] varchar (22),
Incomplete varchar (3),
RequisitionProcState varchar (4),
TtlValRelease money,
PurchRequisitionBlocked varchar (6),
BlockReason varchar (10),
Version varchar (62),
ProcPlant varchar (6),
ExtProcProfile varchar (4),
ExternalProcRefDoc varchar (12),
ExternalProcRefItm int,
PoQtyOnHold int,
ReduceComVal varchar (6),
IssStorLoc varchar (6),
EarmarkedFundsDocNbr varchar (12),
EarmarkedFundsDocItm int,
ReqmtUrgency int,
ReqmtPriorItm int,
AdviceCd varchar (6),
StatusCd bigint,
CsPreqNbr int,
CrossSysPreqItm varchar (6),
CrossSysItmCat varchar (6),
PoQtySender int,
NbrSerialNbr bigint,
MinRemShelfLife int,
PeriodId int,
NoSlocData varchar (22),
IuidRelev varchar (52),
SoLineItmNbr int,
ConfigId varchar (16),
ConfigLine varchar (24),
IncompleteCat varchar (4),
ResPurcReq varchar (4),
CentralContract varchar (12),
CentralContractItm int,
BudgetPeriod varchar (11),
SubconTyp int,
SpStkIdSubcontract varchar (3),
WbsElement varchar (9),
CustNbr varchar (9),
SalesAndDistDocNbr int,
ItmNbrSDDpc varchar (12),
OwnerOfStk varchar (12),
UsGovt int,
StkSegment varchar (12),
ReqmntSegment varchar (3),
FlagOnSpecialBuy varchar (18),
SpecFlag varchar (18)

)

GO


