USE SAP 
GO 


DROP TABLE Bsik
GO 



CREATE TABLE Bsik(
Client varchar (5),
CoCd varchar (5),
Vendor varchar (10),
SpecialGLTransTyp varchar (5),
SpecialGLId varchar (5),
ClrngDt datetime2,
ClrngDoc varchar (10),
AssignNbr bigint,
FY int,
AcctDocNbr bigint,
AcctDocItmNbr int,
DocPostingDt datetime2,
DocDt datetime2,
EnteredOnDt datetime2,
OrderCurr varchar (5),
RefDocNbr varchar (16),
DocTyp varchar (5),
[Period] int,
PostingKey varchar (5),
TrgSpGLId varchar (5),
[Returns] varchar (5),
BusArea varchar (5),
TaxCd varchar (5),
AmtLocalCurr money,
AmtDocCurr money,
LcTax money,
TaxAmount money,
ValDiff1 money,
ValDiff2 money,
[Text] varchar (50),
NbrNotUse varchar (16),
OrderNbr bigint,
Asset varchar (12),
AssetSubNbr varchar (5),
PurchDocNbr bigint,
PurchDocItmNbr int,
GLAcct varchar (10),
GeneralLedgeAmt varchar (10),
FinBudgetItm int,
AcctNbrBranch varchar (10),
BaselineDt datetime2,
PaytTerms varchar (5),
DiscDays1 decimal (5),
DiscDays2 decimal (5),
PmtPeriod decimal (5),
DiscPct1 decimal (5, 3),
DiscPct2 decimal (5, 3),
DiscBase money,
DiscountAmtLocal money,
DiscountAmtDoc money,
PymtMethod varchar (5),
PmntBlock varchar (5),
FixedPmtTerms varchar (5),
HouseBank varchar (5),
PartBankTyp varchar (5),
InvoiceRef varchar (10),
InvoiceFY int,
InvoiceLineItm int,
CustTariffNbr varchar (8),
CustomsDt datetime2,
ScbId varchar (5),
SupCntry varchar (5),
SvcId varchar (5),
DunnBlock varchar (5),
DunningKey varchar (5),
LastDunned datetime2,
DunningLvl int,
DunningArea varchar (5),
DocPostId varchar (5),
DownPaymentId varchar (5),
AddressDataId varchar (5),
IsrDataId varchar (5),
PymtTranId varchar (5),
DistTaxCd1 varchar (5),
AmtLocalCurrTaxDist1 money,
TaxBreakdownAmt1 money,
DistTaxCd2 varchar (5),
AmtLocalCurrTaxDist2 money,
TaxBreakdownAmt2 money,
DistTaxCd3 varchar (5),
AmtLocalCurrTaxDist3 money,
TaxBreakdownAmt3 money,
WTaxCd2 varchar (5),
WTaxBase money,
WithholdingTax money,
DocStat varchar (5),
DocNbrBillExchPmt varchar (10),
FYOfTheBillExch int,
BillofExchPmtReqCoCd varchar (5),
TradingPartnerId varchar (10),
FollowOnDocTyp varchar (5),
VatRegNbr varchar (20),
DestCountry varchar (5),
SupplyingCntry varchar (5),
ExemptNbr varchar (10),
WTaxExempt money,
InvestId varchar (5),
WbsElement int,
CommitmentItm varchar (14),
Network varchar (12),
OperOrderRoutingNbr int,
InternalCounter int,
EuTriangDealId varchar (5),
Amt2LocalCurr money,
Amt3LocalCurr money,
Amt2LocalCurrTaxBreakdown1 money,
Amt2LocalCurrTaxBreakdown2 money,
Amt2LocalCurrTaxBreakdown3 money,
Amt3LocalCurrTaxBreakdown1 money,
Amt3LocalCurrTaxBreakdown2 money,
Amt3LocalCurrTaxBreakdown3 money,
Lc2Tax money,
Lc3Tax money,
Lc2DscAmt money,
Lc3DscAmt money,
ValDiff3 money,
ClearingReversedId varchar (5),
ReasonCd varchar (5),
PmtMethSupl varchar (5),
CostCenter varchar (10),
SequenceNbr int,
ReversalFlagId varchar (5),
OrigReduction money,
BizPartnerRefKey1 varchar (12),
BizPartnerRefKey2 varchar (12),
DocArchiveId varchar (5),
GLCurrency varchar (5),
GLAmount money,
RealEstateKey varchar (8),
SeqNbrAccAss int,
FundsCenter varchar (16),
Fund varchar (10),
ReferenceDtSettle2 datetime2,
NegativePstngId varchar (5),
Payer varchar (10),
ProfitCenter varchar (10),
RefKeyLineItm varchar (20),
InstructKey1 int,
InstructKey2 int,
InstructKey3 int,
InstructKey4 int,
PmtSentBlockId varchar (5),
PmtRef varchar (30),
AutoPymtCur varchar (5),
PmntAmnt money,
BusPlace varchar (5),
SectionCd varchar (5),
DiffRealized1 money,
DiffRealized2 money,
DiffRealized3 money,
PenChargeLc1 money,
PenChargeLc2 money,
PenChargeLc3 money,
PenChargeDocCurr money,
DaysInArrears int,
ReasonDelay varchar (5),
ContractTyp varchar (5),
ContractNbr varchar (13),
FlowTyp varchar (5),
EarmarkedFundsDocNbr varchar (10),
EarmarkedFundsDocItm int,
[Grant] varchar (20),
ItmExecution varchar (5),
AddItmReceivab varchar (5),
RequestNbr varchar (10),
InterestBlock varchar (5),
FunctionalArea varchar (16),
RealEstateMasterDataCd varchar (13),
PartnerPc varchar (10),
LineItmId varchar (5),
ClrgFiscalYr int,
AcctId varchar (5),
AcctAssignCat varchar (5),
AcctAssign varchar (50),
TransferDateLegalDunn datetime2,
JointVenture varchar (10),
EquityGrp varchar (5),
PayrollTyp varchar (5),
MgmtDt varchar (13),
CollectInv int,
BudgetPeriod varchar (10),
);