USE SAP 
GO

DROP TABLE Mchb

CREATE TABLE Mchb (
Client varchar (5),
Material bigint,
Plant int,
StorLoc varchar (6),
BatchNbr varchar (12),
ValTyp varchar (3),
CreatedOn varchar (10),
EnteredBy varchar (14),
LastChange varchar (10),
ChangedBy varchar (14),
YearCurrPeriod int,
CurrPeriod int,
PhysInvBlock varchar (3),
ValUnrestrictUseStk decimal (13, 3),
StkInTrans decimal (13, 3),
StkQualityInspect decimal (13, 3),
TtlStkRestrictBatches decimal (13, 3),
BlockStk decimal (13, 3),
BlockStkReturns decimal (13, 3),
UnrestrUsePrevPeriod decimal (13, 3),
StkTransPrevPeriod decimal (13, 3),
StkQtyInspectPrevPeriod decimal (13, 3),
RestrUsePrevPeriod decimal (13, 3),
BlckStckPrevPeriod decimal (13, 3),
BlckStkReturnPrevPeriod decimal (13, 3),
WarehouseStkCurrYr varchar (5),
QualInspStkCurrYr varchar (5),
RestrictedUseCurrYr varchar (5),
BlockedStkCurrYr varchar (5),
WarehouseStkPrevYr varchar (5),
QualInspStkPrevYr varchar (5),
RestrictedUsePrevYr varchar (5),
BlockedStkPrevYr varchar (5),
CtryOfOrigin varchar (5),
LastCountDt varchar (10),
FYCurrPhysInvId int,
MchbhRecAlreadyExists varchar (3),
StorSegment varchar (18),
)