
Drop Table sap.dbo.KNA1;

CREATE TABLE sap.dbo.Kna1
(
Client varchar (4),
SoldToPartyId varchar (30),
DestCountry varchar (4),
Name1 varchar (51),
Name2 varchar (51),
City varchar (51),
PostalCd varchar (21),
Region varchar (4),
SortTerm varchar (11),
StreetAddress varchar (51),
TelephoneNbr varchar (17),
FaxNbr varchar (32),
OneTimeAcctId varchar (2),
[Address] varchar (11),
MatchCodeSearch1 varchar (51),
MatchCodeSearch2 varchar (51),
MatchCodeSearch3 varchar (51),
Title varchar (16),
OrderBlock varchar (51),
ExpressStation varchar (51),
TrainStation varchar (51),
LocNbrPart1 int,
LocNbrPart2 int,
AuthGrp varchar (5),
IdustryKey varchar (5),
CheckDigit int,
DataCommLineNbr varchar (15),
CreatedOn datetime2,
CreatedBy varchar (13),
UnloadingPtsId varchar (2),
CentralBillBlock varchar (3),
AcctNbrFiscalAddress varchar (11),
WorkingTimes varchar (3),
AltPayer varchar (11),
CorpGrp varchar (11),
AcctGrp varchar (5),
CustClass varchar (3),
Vendor varchar (11),
DlvryBlock varchar (3),
CityCoordinates varchar (11),
DeleteFlag varchar (2),
Name3 varchar (36),
Name4 varchar (36),
NielsenId varchar (3),
District varchar (36),
PoBox varchar (11),
PoBoxPostalCd varchar (11),
CountyCd varchar (4),
CityCd varchar (5),
RegionalMarket varchar (6),
PostingBlock varchar (2),
[Language] varchar (2),
TaxNbr1 varchar (17),
TaxNbr2 varchar (12),
EqualizationTaxId varchar (2),
VatLiability varchar (2),
TeleboxNbr varchar (16),
SecondTelephoneNbr varchar (17),
TeletexNbr varchar (31),
TelexNbr varchar (31),
TransportZone varchar (11),
AltPayerId varchar (2),
TradingPartnerId varchar (7),
VatRegNbr varchar (21),
CompetitorId varchar (2),
SalesPartnerId varchar (2),
ProspectId varchar (2),
CustTyp4Id varchar (2),
DefaultSoldParty varchar (2),
LegalStatus varchar (3),
IdustryCd1 varchar (11),
IdustryCd2 varchar (11),
IdustryCd3 varchar (11),
IdustryCd4 varchar (11),
IdustryCd5 varchar (11),
InitialContact varchar (11),
AnnualSales money,
SalesYear int,
Currency varchar (6),
NbrEmployeesYearly int,
NbrEmployeesGivenYear int,
Attribute1 varchar (3),
Attribute2 varchar (3),
Attribute3 varchar (3),
Attribute4 varchar (3),
Attribute5 varchar (3),
Attribute6 varchar (4),
Attribute7 varchar (4),
Attribute8 varchar (4),
Attribute9 varchar (4),
Attribute10 varchar (4),
NaturalPerson varchar (2),
AnnualSales1 money,
TaxJur1 varchar (16),
FYVariant varchar (3),
UsageId varchar (4),
ByCustInspect varchar (2),
AfterDlvryInspect varchar (2),
RefAcctGrp varchar (5),
POBoxCity varchar (36),
Plant varchar (5),
DMEId varchar (2),
InstructionKey varchar (3),
DataTransferStatus varchar (2),
HierAssign int,
PmtBlock varchar (2),
LabCustGrp varchar (11),
NbrNonMilitUse varchar (2),
MilitaryUse varchar (2),
ConditionGrp1 varchar (3),
ConditionGrp2 varchar (3),
ConditionGrp3 varchar (3),
ConditionGrp4 varchar (3),
ConditionGrp5 varchar (3),
AltPayerAccNbrId varchar (2),
TaxTyp varchar (3),
TaxNbrTyp varchar (3),
TaxNbr3 varchar (19),
TaxNbr4 varchar (19),
TaxNbr5 varchar (61),
ICMSExempt varchar (2),
IPIExempt varchar (2),
SubtTribGrp varchar (4),
CFOPCat varchar (3),
ICMSLaw varchar (4),
IPILaw varchar (4),
BiochemWarfare varchar (2),
NuclNbrNonProlif varchar (2),
NatlSecurIty varchar (2),
MissileTechId varchar (2),
SalesBlock varchar (3),
[URL] varchar (133),
RepsName varchar (11),
TypOfBus varchar (31),
TypOfIdustry varchar (31),
StatChangeAuthCentral varchar (2),
ConfDt datetime2,
LastConfTime varchar (50),
DelBlock varchar (2),
ConsumerId varchar (2),
BusPurposeCompleteFlag varchar (2),
SuframaCode varchar (10),
RGNbr varchar (12),
IssuedBy varchar (4),
[State] varchar (3),
RGIssueDt datetime2,
RICNbr int,
ForeignNationalReg varchar (11),
RNEIssueDt datetime2,
CNAE varchar (8),
LegalNature int,
CRTNbr varchar (2),
ICMSTaxpayer varchar (3),
IdustryMainTyp varchar (3),
TaxDeclarationTyp varchar (3),
CoSize varchar (3),
DeclRegPISCOFINS varchar (3),
MaxStackHghtVSO decimal (13, 3),
PkmLengthUnitVSO varchar (4),
CustRelatedVSO varchar (2),
PackMatCustVSO varchar (19),
NbrLayersInPaletVSO int,
MatSpec varchar (2),
PackOnlyOnePkmVSO varchar (2),
SidePreferenceVSO int,
FBPreferenceVSO int,
CollectUnloadPointVSO varchar (11),
AgencyLocCd varchar (9),
PmtOffice varchar (6),
FeeSchedule varchar (5),
DunsNbr varchar (10),
DunsPlus4 varchar (5),
ProcessorGrp varchar (11),
SubledgerProced varchar (21),
Name5 varchar (36),
Name6 varchar (36),
Name7 varchar (36),
FirstName varchar (36),
Title1 varchar (21),
HouseNbr varchar (7),
Street varchar (29),
Description1 varchar (51),
Description2 varchar (51),
Description3 varchar (51),
Description4 varchar (51),
Description5 varchar (51),
ActiveCust varchar (2),
MdmId varchar (15),
DeactivationReason varchar (5),
PartyTyp varchar (3),
AvnetLogoPrintFlag varchar (2),
InsuranceChargeCd varchar (2),
FuelSurcharge1 varchar (2),
HandlingCharge varchar (2),
AlternateCountryName varchar (2),
Hazmat varchar (3),
HpVARIDNbr varchar (16),
IbmCustContract varchar (16),
ITARRestricted varchar (2),
ForeignGovernment varchar (2),
CustGrowthTyp varchar (2),
RelatedParty varchar (2),
TaxExemptFlag varchar (2),
SmallDisadvantageBus varchar (2),
UserTyp varchar (2),
ReplenishCd varchar (2),
ExportCd varchar (3),
RoutedCust varchar (3),
DutiesTaxesLoc varchar (3),
DutyAndTaxesAcctNbr varchar (13),
ActionDefectParts varchar (2),
ExportTaxId varchar (13),
ImportTaxId varchar (25),
DemandCreationClass varchar (3),
ExemptFromAtpOverride varchar (2),
PlantShutdownStartDt datetime2,
PlantShutdownEndDt datetime2,
SoldToDt datetime2,
ShipTyp varchar (2),
EndUse varchar (2),
MinLineItmVal money,
MinMatGP int,
MinDesignWinMatGP int,
MinBusUnitMatGP int,
RemoteRegion varchar (3),
RemoteRegionSapAccNbr varchar (11),
RemoteRegionAvnet varchar (3),
StateOfAssuranOrigAttachDt datetime2,
StateOfAssuranAttachDt datetime2,
StateOfAssuranAttachId varchar (2),
StateOfAssuranReq varchar (2),
BankRefAttachDt datetime2,
BankRefAttachedId varchar (2),
BankRefReq varchar (2),
TradeRefAttachDt datetime2,
TradeRefAttach varchar (2),
TradeRefReq varchar (2),
TaxDocAttachDt datetime2,
TaxDocAttach varchar (2),
TaxDocReq varchar (2),
EndUseStatementAttachDt datetime2,
EndUseStatementAttach varchar (2),
EndUseStatementReq varchar (2),
CreditLimitException money,
NonTaxableRequest varchar (2),
XilinxSoldTo varchar (11),
XilinxShipTo varchar (31),
XilinxHubId varchar (11),
InvoiceListSplit varchar (2),
OriginNationalAcctNbr varchar (5),
SOASoldToParty varchar (11),
CustBusPlan varchar (2),
NonDisclosureAgree varchar (2),
OutsideLookingInAcct varchar (2),
GlobalCustNbr varchar (11),
SourceOfExtBPNbr varchar (5),
DBNbrDUNS varchar (10),
DeniedPartyBlockCd varchar (2),
VertexIdNbr varchar (8),
EnterpriseCustNbr varchar (17),
DpcDt decimal (15),
CustSince datetime2
PRIMARY KEY (Client, SoldToPartyId)
)