USE [NascarProd]
GO

/****** Object:  Table [dbo].[NascarExportLine]    Script Date: 10/2/2017 3:05:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NascarExportLine](
	[NASCAR_BATCH_EXPORT_ID] [float] NOT NULL,
	[QUOTE_ID] [float] NOT NULL,
	[LINE_ITEM_NO] [float] NOT NULL,
	[LINE_ITEM_STATUS] [nvarchar](1) NOT NULL,
	[SOLD_TO_CUST] [nvarchar](100) NOT NULL,
	[SHIP_TO_CUST] [nvarchar](100) NOT NULL,
	[CUST_PART] [nvarchar](50) NULL,
	[CUST_REQ_MFG] [nvarchar](50) NULL,
	[REQUESTED_PART] [nvarchar](50) NULL,
	[MFG_CODE] [nvarchar](50) NULL,
	[REQ_PART_DES] [nvarchar](255) NULL,
	[QUOTED_MFG] [nvarchar](100) NULL,
	[QUOTED_PART] [nvarchar](50) NULL,
	[TLA_NO] [nvarchar](50) NULL,
	[SAP_MATERIAL_ID] [nvarchar](50) NULL,
	[REQUESTED_TLA] [nvarchar](50) NULL,
	[TLA_TYPE_CD] [nvarchar](100) NULL,
	[TLA_STATUS] [nvarchar](50) NULL,
	[TLA_STATUS_DT] [datetime2](7) NULL,
	[MATERIAL_PLANNING_STRATEGY] [nvarchar](50) NULL,
	[MFG_MODIFIED_FL] [nvarchar](1) NULL,
	[MATCH_SOURCE] [nvarchar](50) NULL,
	[TARGET_PRICE] [float] NULL,
	[ACTIVITY_UNIT] [float] NULL,
	[QUANTITY_1] [float] NULL,
	[QUANTITY_2] [float] NULL,
	[QUANTITY_3] [float] NULL,
	[QUOTED_RESALE_1] [float] NULL,
	[QUOTED_RESALE_2] [float] NULL,
	[QUOTED_RESALE_3] [float] NULL,
	[APPROVED_RESALE_1] [float] NULL,
	[APPROVED_RESALE_2] [float] NULL,
	[APPROVED_RESALE_3] [float] NULL,
	[AUTH_REQ] [nvarchar](10) NOT NULL,
	[BOOK_RESALE] [float] NULL,
	[MATERIAL_GP] [float] NULL,
	[RESALE_SOURCE] [nvarchar](50) NULL,
	[QAS] [float] NULL,
	[ATP_DT] [datetime2](7) NULL,
	[AFA_SERIAL_NO] [nvarchar](50) NULL,
	[EXTENDED_LI_VALUE] [float] NULL,
	[PRICING_STRATEGY] [nvarchar](50) NULL,
	[COST_TYPE] [nvarchar](50) NULL,
	[SALES_COST] [float] NULL,
	[DISTI_COST] [float] NULL,
	[DISTI_RESALE] [float] NULL,
	[COST] [float] NULL,
	[PRICE_TYPE_1] [nvarchar](100) NULL,
	[PRICE_TYPE_2] [nvarchar](100) NULL,
	[PRICE_TYPE_3] [nvarchar](100) NULL,
	[SUPPLIER_LEAD_TIME] [float] NULL,
	[APPROVED_LT_1] [float] NULL,
	[APPROVED_LT_2] [float] NULL,
	[APPROVED_LT_3] [float] NULL,
	[QUOTED_LT] [float] NULL,
	[SUPPLIER_QUOTE_NO] [nvarchar](15) NULL,
	[APPROVED_MIN_1] [float] NULL,
	[APPROVED_MIN_2] [float] NULL,
	[APPROVED_MIN_3] [float] NULL,
	[APPROVED_MULT_1] [float] NULL,
	[APPROVED_MULT_2] [float] NULL,
	[APPROVED_MULT_3] [float] NULL,
	[SMPQ] [float] NULL,
	[COMMODITY_CODE] [nvarchar](50) NULL,
	[PART_HAZ_ATTR] [nvarchar](50) NULL,
	[SOLE_SOURCE] [nvarchar](50) NULL,
	[MATERIAL_LIFE_CYCLE] [nvarchar](50) NULL,
	[NCNR] [nvarchar](50) NULL,
	[CUSTOM_PRODUCT] [nvarchar](50) NULL,
	[STOCK_PROFILE] [nvarchar](100) NULL,
	[ABC_INDICATOR] [nvarchar](50) NULL,
	[LAST_TIME_BUY_DT] [datetime2](7) NULL,
	[LAST_TIME_RETURN_DT] [datetime2](7) NULL,
	[LAST_TIME_SHIP_DT] [datetime2](7) NULL,
	[MATERIAL_PACKAGING_TYPE] [nvarchar](50) NULL,
	[REGISTRABLE] [nvarchar](100) NULL,
	[REGISTRATION_NO] [nvarchar](35) NULL,
	[REGISTRATION_ID] [nvarchar](50) NULL,
	[REGISTRATION_STATUS] [nvarchar](50) NULL,
	[CUST_LAST_BUY_DT] [datetime2](7) NULL,
	[CUST_LAST_BUY_QT] [float] NULL,
	[CUST_LAST_BUY_RES] [float] NULL,
	[COMMENTS] [nvarchar](1024) NULL,
	[APPROVED_COST_1] [float] NULL,
	[APPROVED_COST_2] [float] NULL,
	[APPROVED_COST_3] [float] NULL,
	[APPROVED_MO_1] [float] NULL,
	[APPROVED_MO_2] [float] NULL,
	[APPROVED_MO_3] [float] NULL,
	[AGREEMENT_TYPE] [nvarchar](50) NULL,
	[AUTHORIZATION_NO] [nvarchar](20) NULL,
	[CONSIGNMENT_AUTH_NO] [nvarchar](50) NULL,
	[AGREEMENT_COST_TYPE] [nvarchar](50) NULL,
	[AGREEMENT_COST] [float] NULL,
	[AGREEMENT_QTY] [float] NULL,
	[AUTH_EXP_DATE] [datetime2](7) NULL,
	[AGREEMENT_ADJUSTED_COST] [float] NULL,
	[END_CUSTOMER_ACCOUNT_NO] [nvarchar](100) NULL,
	[END_CUSTOMER_LOCATION] [nvarchar](256) NULL,
	[END_CUSTOMER_NAME] [nvarchar](100) NULL,
	[END_USER_NAME_ACCOUNT_NO] [nvarchar](100) NULL,
	[APPROVED_EXPIRATION_DT_1] [datetime2](7) NULL,
	[APPROVED_EXPIRATION_DT_2] [datetime2](7) NULL,
	[APPROVED_EXPIRATION_DT_3] [datetime2](7) NULL,
	[FOLLOW_UP_DT] [datetime2](7) NULL,
	[SHIP_TO_LOCATION] [nvarchar](256) NULL,
	[INVENTORY_MESSAGE] [nvarchar](256) NULL,
	[SALES_MESSAGE] [nvarchar](256) NULL,
	[ADDITIONAL_UNIT_COST] [float] NULL,
	[BEST_REPLACEMENT_COST] [float] NULL,
	[BOOK_COST_1] [float] NULL,
	[INTERNAL_PRICE] [float] NULL,
	[GROUP_CD] [nvarchar](9) NULL,
	[LATEST_REFRESH_DT] [datetime2](7) NULL,
	[REQ_SAP_MATERIAL_ID] [nvarchar](50) NULL,
	[SOLD_AT_PREMIER] [nvarchar](50) NULL,
	[BKN_SAP_MATERIAL] [nvarchar](50) NULL,
	[ASSIGNED_TO] [nvarchar](50) NULL,
	[SALES_COST_SRC] [nvarchar](50) NULL,
	[SUB_PROD_CNT] [float] NULL,
	[NASCAR_EXP_DT] [datetime2](7) NOT NULL,
	[IMPORT_ERROR] [nvarchar](1024) NULL,
	[APPL_CREATE_DT] [datetime2](7) NOT NULL,
	[WEB_RESALE] [float] NULL,
	[PART_MODIFIED_FL] [nvarchar](1) NULL,
	[MODIFIED_PART] [nvarchar](1) NULL,
	[MODIFIED_MFG] [nvarchar](3) NULL,
	[SMOQ] [float] NULL
) ON [PRIMARY]

GO


